export const DATA = 
[
  {
    place_id: "1",
    place_name: "Monumen Nasional",
    description:
      "Monumen Nasional atau yang populer disingkat dengan Monas atau Tugu Monas adalah monumen peringatan setinggi 132 meter (433 kaki) yang didirikan untuk mengenang perlawanan dan perjuangan rakyat Indonesia untuk merebut kemerdekaan dari pemerintahan kolonial Hindia Belanda. Pembangunan monumen ini dimulai pada tanggal 17 Agustus 1961 di bawah perintah presiden Soekarno dan dibuka untuk umum pada tanggal 12 Juli 1975. Tugu ini dimahkotai lidah api yang dilapisi lembaran emas yang melambangkan semangat perjuangan yang menyala-nyala. Monumen Nasional terletak tepat di tengah Lapangan Medan Merdeka, Jakarta Pusat.",
    place_image:
      "https://cdn06.pramborsfm.com/storage/app/media/Prambors/Editorial/Monas-20220616154927.jpg?tr=w-800",
    category: "Budaya",
    city: "Jakarta",
    price: "20000",
    rating: "4.6",
    time_minutes: "15",
    coordinate: "{'lat': -6.1753924, 'lng': 106.8271528}",
    lat: "-6.175392",
    long: "106.827152",
  },
  {
    place_id: "2",
    place_name: "Kota Tua",
    description:
      "Kota tua di Jakarta, yang juga bernama Kota Tua, berpusat di Alun-Alun Fatahillah, yaitu alun-alun yang ramai dengan pertunjukan rutin tarian tradisional. Museum Sejarah Jakarta adalah bangunan era Belanda dengan lukisan dan barang antik, sedangkan Museum Wayang memamerkan boneka kayu khas Jawa. Desa Glodok, atau Chinatown, terkenal dengan makanan kaki lima, seperti pangsit dan mi goreng. Di dekatnya, terdapat sekunar dan kapal penangkap ikan di pelabuhan Sunda Kelapa yang kuno",
    place_image:
      "https://1.bp.blogspot.com/-ealjc3VkEuM/YJMoADRteII/AAAAAAAADWE/nmwZ_zRlRR85SCQ9aQjLjoNKuvJZC4VhwCLcBGAsYHQ/s0/KotaTua.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    time_minutes: "90",
    coordinate: "{'lat': -6.137644799999999, 'lng': 106.8171245}",
    lat: "-6.137644",
    long: "106.817124",
  },
  {
    place_id: "3",
    place_name: "Dunia Fantasi",
    description:
      "Dunia Fantasi atau disebut juga Dufan adalah tempat hiburan yang terletak di kawasan Taman Impian Jaya Ancol, Jakarta Utara, Indonesia. Dufan diresmikan dan dibuka pada tanggal 29 Agustus 1985.",
    place_image:
      "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit19201280gsm/events/2023/02/20/059dcec7-f922-4ab8-871a-61285116f8ae-1676890139982-312ccd6af8b478b0a103041a830d2472.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "270000",
    rating: "4.6",
    time_minutes: "360",
    coordinate: "{'lat': -6.125312399999999, 'lng': 106.8335377}",
    lat: "-6.125312",
    long: "106.833537",
  },
  {
    place_id: "4",
    place_name: "Taman Mini Indonesia Indah (TMII)",
    description:
      "Taman Mini Indonesia Indah merupakan suatu kawasan taman wisata bertema budaya Indonesia di Jakarta Timur. Area seluas kurang lebih 150 hektare atau 1,5 kilometer persegi ini terletak pada koordinat 6°18′6.8″LS,106°53′47.2″BT",
    place_image:
      "https://akcdn.detik.net.id/visual/2021/04/08/wisata-tmii_169.jpeg?w=650",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "10000",
    rating: "4.5",
    coordinate: "{'lat': -6.302445899999999, 'lng': 106.8951559}",
    lat: "-6.302445",
    long: "106.895155",
  },
  {
    place_id: "5",
    place_name: "Atlantis Water Adventure",
    description:
      "Atlantis Water Adventure atau dikenal dengan Atlantis Ancol akan menyuguhkan petualangan wisata air tak terlupakan. Tempat Wisata bertemakan permainan air dengan luas 5 hektar ini memberi sensasi petualangan di 8 kolam utama. Yaitu kolam Antila, Plaza Atlas, Poseidon, Aquarius, Octopus, Kiddy Pool, dan Atlantean. Berlokasi di kawasan Ancol Jakarta Baycity, Atlantis bisa menjadi pilihan destinasi yang pas untuk wisata berenang.",
    place_image:
      "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit19201280gsm/events/2022/02/03/18ad925e-eaee-4d8b-862f-ffb675637678-1643885991656-bea8eb0554962bd17c405ce76f5bfcb9.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "94000",
    rating: "4.5",
    time_minutes: "60",
    coordinate: "{'lat': -6.12419, 'lng': 106.839134}",
    lat: "-6.12419",
    long: "106.839134",
  },
  {
    place_id: "6",
    place_name: "Taman Impian Jaya Ancol",
    description:
      "Taman Impian Jaya Ancol merupakan sebuah objek wisata di Jakarta Utara.\\n\\n",
    place_image:
      "https://images.bisnis.com/posts/2022/05/05/1530147/ancol3.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "25000",
    rating: "4.5",
    time_minutes: "10",
    coordinate: "{'lat': -6.117333200000001, 'lng': 106.8579951}",
    lat: "-6.117333",
    long: "106.857995",
  },
  {
    place_id: "7",
    place_name: "Kebun Binatang Ragunan",
    description:
      "Kebun Binatang Ragunan adalah sebuah kebun binatang yang terletak di daerah Ragunan, Pasar Minggu, Jakarta Selatan, Indonesia. Kebun binatang seluas 140 hektare ini didirikan pada tahun 1864. Di dalamnya terdapat berbagai koleksi yang terdiri dari 295 spesies dan 4040 spesimen.\\nRagunan sempat ditutup selama sekitar tiga minggu sejak 19 September 2005 karena hewan-hewan di dalamnya ada yang terinfeksi flu burung, tetapi dibuka kembali pada 11 Oktober 2005.Kebun binatang ini memiliki banyak spesies hewan yang langka antara lain kakatua, orangutan, gorila, anoa dan gajah",
    place_image:
      "https://indonesiainside.id/wp-content/uploads/2020/05/04_KB-Ragunan_280520_Zubeir.jpeg",
    category: "Cagar Alam",
    city: "Jakarta",
    price: "4000",
    rating: "4.5",
    coordinate: "{'lat': -6.3124593, 'lng': 106.8201865}",
    lat: "-6.312459",
    long: "106.820186",
  },
  {
    place_id: "8",
    place_name: "Ocean Ecopark",
    description:
      "Ocean Ecopark Salah satu zona rekreasi Ancol yang menawarkan ruang terbuka hijau serta pengalaman dan tidak melupakan sisi pendidikan bagi para pengunjung. Beragam aktivitas dan wahana seru yang bisa dimainkan di tempat rekreasi keluarga, beberapa diantaranya : Outbondholic, Rumah Energy, Rumah Lebah, Kano, Paintball, Outbondholic, Eco-Market, Learning Farm, Eco-Bike, Faunaland. Kalau berencana berwisata ke Ocean Eco Park ancol tidak perlu khawatir dengan harga tiket masuknya. Karena harga tiket masuk Ocean Eco Park ditawarkan dengan harga yang masih terjangkau.r",
    place_image:
      "https://asset.kompas.com/crops/ngQW39td-HaDs8we0gkyZ0PmQpU=/0x38:1000x704/750x500/data/photo/2020/11/06/5fa4d11798221.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "180000",
    rating: "4",
    coordinate: "{'lat': -6.125801699999999, 'lng': 106.8363249}",
    lat: "-6.125801",
    long: "106.836324",
  },
  {
    place_id: "9",
    place_name: "Pelabuhan Marina",
    description:
      "Pelabuhan Marina Ancol berada di kawasan Taman Impian Jaya Ancol, Jakarta. Pelabuhan yang biasa disebut Dermaga Marina Ancol ini adalah kawasan yang tidak hanya untuk keperluan penyeberangan saja, tetapi juga dikembangkan untuk banyak hal, seperti wisata air, olahraga air maupun wahana bermain. Fungsi utama dari pelabuhan ini adalah untuk melayani para penumpang yang ingin menyeberang menuju ke kepulauan Seribu, begitu juga sebaliknya. Banyak orang yang berada di Jakarta dan sekitarnya, menjadikan kepulaun Seribu sebagai tujuan wisata yang utama. Liburan di Pulau Seribu memang mampu menghilangkan kepenatan bekerja di kota metropolitan, sembari menikmati keindahan pantai yang masih terjaga dengan baik. Marina Ancol berada di Jakarta Utara atau secara lengkap beralamat di Kota Tua, Ancol, Pademangan, Kota Jakarta. Sangat mudah menuju ke tempat ini karena tidak terlalu jauh dari pusat kota. Selain itu, ada banyak transportasi umum yang menuju ke tempat ini atau bisa juga menggunakan jasa transportasi online.",
    place_image:
      "https://bisniswisata.co.id/wp-content/uploads/2018/04/dermaga-marina.jpg",
    category: "Bahari",
    city: "Jakarta",
    price: "175000",
    rating: "4.4",
    coordinate: "{'lat': 1.07888, 'lng': 103.931398}",
    lat: "1.07888",
    long: "103.931398",
  },
  {
    place_id: "10",
    place_name: "Pulau Tidung",
    description:
      "Pulau Tidung adalah salah satu kelurahan di kecamatan Kepulauan Seribu Selatan, Kabupaten Kepulauan Seribu, Jakarta, Indonesia.",
    place_image:
      "https://ngetripkemana.com/wp-content/uploads/2022/08/Pulau-Tidung_Pic1.jpg",
    category: "Bahari",
    city: "Jakarta",
    price: "150000",
    rating: "4.5",
    coordinate: "{'lat': -5.803205300000001, 'lng': 106.5237907}",
    lat: "-5.803205",
    long: "106.523790",
  },
  {
    place_id: "11",
    place_name: "Pulau Bidadari",
    description:
      "Pulau Bidadari merupakan salah satu resor di Kabupaten Kepulauan Seribu, Jakarta. Sebelum bernama Pulau Bidadari, pulau ini memiliki dua nama yaitu Pulau Sakit dan Pulau Purmerend",
    place_image:
      "https://pulau-seribu.com/wp-content/uploads/wisata-murah-pulau-bidadari-kepulauan-seribu-jakarta.jpg",
    category: "Bahari",
    city: "Jakarta",
    price: "5000",
    rating: "4.6",
    coordinate: "{'lat': -6.035832999999999, 'lng': 106.746944}",
    lat: "-6.035833",
    long: "106.746944",
  },
  {
    place_id: "12",
    place_name: "Pulau Pari",
    description:
      "Pulau Pari adalah sebuah pulau yang terletak di Kepulauan Seribu di Daerah Khusus Ibukota Jakarta, Indonesia.r",
    place_image:
      "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/events/2020/12/23/427b9167-b687-4722-8088-f83c16270901-1608719103733-001279551f07d8604666357d0ae946c8.jpg",
    category: "Bahari",
    city: "Jakarta",
    price: "150000",
    rating: "4",
    coordinate: "{'lat': -5.9074328, 'lng': 106.5863989}",
    lat: "-5.907432",
    long: "106.586398",
  },
  {
    place_id: "13",
    place_name: "Pulau Pramuka",
    description:
      "Pulau Pramuka merupakan salah satu pulau yang berada dalam gugusan Kepulauan Seribu. Pulau ini merupakan pusat administrasi dan pemerintahan Kabupaten Administrasi Kepulauan Seribu. Pulau Pramuka termasuk ke dalam wilayah Kelurahan Pulau Panggang.",
    place_image:
      "https://pict.sindonews.net/dyn/850/pena/news/2022/04/13/156/741947/pesona-keindahan-pulau-pramuka-ada-wisata-diving-serta-penangkaran-hiu-qsh.jpg",
    category: "Bahari",
    city: "Jakarta",
    price: "5000",
    rating: "4.2",
    coordinate: "{'lat': -5.745962, 'lng': 106.6136577}",
    lat: "-5.745962",
    long: "106.613657",
  },
  {
    place_id: "14",
    place_name: "Pulau Pelangi",
    description:
      "Pulau Pelangi adalah sebuah pulau yang terletak di Kepulauan Seribu di Daerah Khusus Ibukota Jakarta, Indonesia. Pulau Pelangi adalah sebuah pulau yang terletak di Kepulauan Seribu di Daerah Khusus Ibukota Jakarta, Indonesia, Pulau Pelangi biasa disebut Pulau Petondan Besar ( Pelangi Island ) merupakan pulau resort yang sesuai untuk berlibur. Pulau Resort ini mempunyai konsep natural, karena sebagian wilayahnya di penuhi dengan rerimbunan pohon yang menyejukan mata, Keindahan alam dan lautnya layak untuk dikunjungi. Dikelilingi oleh rimbunan pohon dan laut berwarana biru jernih membuat suasanan sejuk dan nyaman. Kondisi yang ideal untuk wisata bersama keluarga. Dengan akomodasi yang langsung menghadap ke laut membuat turis betah berlama-lama di Pulau Pelangi.\\nMenurut informasi, Pulau Pelangi atau Pulau Petondan Besar merupakan pulau yang berada pada gugusan Kepulauan Seribu. Secara administratif termasuk dalam wilayah Kabupaten Administratif Kepulauan Seribu provinsi DKI Jakarta. Bersamaan dengan Pulau Petondan Kecil merupakan sebuah resort berlibur. Letaknya berdekatan dengan gugusan yang sama dengan Pulau Kelor dan Pulau Kelapa.\\nUntuk mencapai Pelangi Resort dibutuhkan waktu 90 menit perjalanan dari dermaga Pantai Mutiara. Terdapat kapal speedboat khusus di pier R1 Pantai Mutiara yang membawa penumpang kesana. Letaknya 60 – 70 km dari Pantai Mutiara memang lumayan jauh. Namun perjalanan anda terbayar lunas begitu sampai di Pulau Pelangi.r",
    place_image:
      "https://marketingpulauseribu.com/assets/images/paket/_58230.jpg",
    category: "Bahari",
    city: "Jakarta",
    price: "900000",
    rating: "4.8",
    coordinate: "{'lat': -5.587055, 'lng': 106.5885}",
    lat: "-5.587055",
    long: "106.5885",
  },
  {
    place_id: "15",
    place_name: "Pasar Seni",
    description:
      "Pasar Seni merupakan Pusat kerajinan dan kesenian yang menjadi wadah bagi seniman berbakat untuk menyalurkan kerajinan seni yang mereka miliki. Seniman dapat bertemu dengan para kolektor seni dan pengusaha untuk saling berbagi informasi dan memasarkan produk yang dimiliki. Didirikan awal tahun 1977, dengan peletakan batu pertama oleh Bang Ali Sadikin, Gubernur pertama DKI Jakarta, tepatnya pada bulan Juli 1977. Dan diresmikan oleh Gubernur H. Tjokropanolo pada tanggal 17 Desember 1977. Sejak diresmikan Pasar Seni, mendapat sambutan positif bagi pada pecinta seni yang ada.",
    place_image:
      "https://www.goodnewsfromindonesia.id/uploads/images/2020/07/1108132020-Goodnewsfromindonesia-GNFI-pintu-gerbang-pasar-seni-ancol.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.4",
    time_minutes: "90",
    coordinate: "{'lat': -6.1766868, 'lng': 106.8417666}",
    lat: "-6.176686",
    long: "106.841766",
  },
  {
    place_id: "16",
    place_name: "Jembatan Kota Intan",
    description:
      "Jembatan Kota Intan adalah jembatan tertua di Indonesia yang dibangun pada tahun 1628 oleh pemerintah Vereenigde Oostindische Compagnie atau VOC, atau masyarakat kita lebih familiar dengan sebutan Kumpeni. Jembatan itu kini terletak di Kali Besar kawasan Kota Tua wilayah Jakarta Barat dan berada di bawah pengelolaan Dinas Pariwisata dan Kebudayaan Provinsi DKI Jakarta.",
    place_image:
      "https://dinaskebudayaan.jakarta.go.id/disbuddki/uploads/default/files/Jembatan_Kota_Intan.JPG",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.3",
    coordinate: "{'lat': -6.1314572, 'lng': 106.8106169}",
    lat: "-6.131457",
    long: "106.810616",
  },
  {
    place_id: "17",
    place_name: "Museum Fatahillah",
    description:
      "Museum Fatahillah memiliki nama resmi Museum Sejarah Jakarta adalah sebuah museum yang terletak di Jalan Taman Fatahillah No. 1, Jakarta Barat dengan luas lebih dari 1.300 meter persegi.\\nBangunan ini dahulu merupakan balai kota Batavia (bahasa Belanda: Stadhuis van Batavia) yang dibangun pada tahun 1707-1710 atas perintah Gubernur-Jendral Joan van Hoorn. Bangunan ini menyerupai Istana Dam di Amsterdam, terdiri atas bangunan utama dengan dua sayap di bagian timur dan barat serta bangunan sanding yang digunakan sebagai kantor, ruang pengadilan, dan ruang-ruang bawah tanah yang dipakai sebagai penjara. Pada tanggal 30 Maret 1974, bangunan ini kemudian diresmikan oleh bapak Ali Sadikin sebagai Museum Sejarah Jakarta.",
    place_image:
      "https://dinaskebudayaan.jakarta.go.id/disbuddki/uploads/default/files/Museum_Fatahillah_1.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.4",
    coordinate: "{'lat': -6.136448899999999, 'lng': 106.8130661}",
    lat: "-6.136448",
    long: "106.813066",
  },
  {
    place_id: "18",
    place_name: "Museum Bank Indonesia",
    description:
      "Museum Bank Indonesia adalah sebuah museum di Jakarta, Indonesia yang terletak di Jl. Pintu Besar Utara No.3, Jakarta Barat (depan stasiun Beos Kota), dengan menempati area bekas gedung Bank Indonesia Kota yang merupakan cagar budaya peninggalan De Javasche Bank yang beraliran neo-klasikal, dipadu dengan pengaruh lokal, dan dibangun pertama kali pada tahun 1828.\\nPada tahun 1625, di tempat ini pernah dibangun sebuah gereja sederhana untuk umat Protestan. Pada tahun 1628, gereja ini dibongkar karena digunakan untuk tempat meriam besar ketika puluhan ribu tentara Sultan Agung menyerang Batavia untuk pertama kali.Museum ini menyajikan informasi peran Bank Indonesia dalam perjalanan sejarah bangsa yang dimulai sejak sebelum kedatangan bangsa barat di Nusantara hingga terbentuknya Bank Indonesia pada tahun 1953 dan kebijakan-kebijakan Bank Indonesia, meliputi pula latar belakang dan dampak kebijakan Bank Indonesia bagi masyarakat sampai dengan tahun 2005. Penyajiannya dikemas sedemikian rupa dengan memanfaatkan teknologi modern dan multi media, seperti display elektronik, panel statik, televisi plasma, dan diorama sehingga menciptakan kenyamanan pengunjung dalam menikmati Museum Bank Indonesia. Selain itu terdapat pula fakta dan koleksi benda bersejarah pada masa sebelum terbentuknya Bank Indonesia, seperti pada masa kerajaan-kerajaan Nusantara, antara lain berupa koleksi uang numismatik yang ditampilkan juga secara menarik.\\nPeresmian Museum Bank Indonesia dilakukan melalui dua tahap, yaitu peresmian tahap I dan mulai dibuka untuk masyarakat (soft opening) pada tanggal 15 Desember 2006 oleh Gubernur Bank Indonesia saat itu, Burhanuddin Abdullah, dan peresmian tahap II (grand opening) oleh Presiden RI Susilo Bambang Yudhoyono, pada tanggal 21 Juli 2009.\\nMuseum Bank Indonesia buka setiap hari kecuali Senin dan hari libur nasional.",
    place_image:
      "https://dinaskebudayaan.jakarta.go.id/disbuddki/uploads/default/files/Museum_Bank_Indonesia.JPG",
    category: "Budaya",
    city: "Jakarta",
    price: "2000",
    rating: "4.7",
    coordinate: "{'lat': -6.137127, 'lng': 106.813005}",
    lat: "-6.137127",
    long: "106.813005",
  },
  {
    place_id: "19",
    place_name: "Kidzania",
    description:
      "KidZania adalah sebuah waralaba swasta Meksiko berupa pusat hiburan keluarga yang saat ini beroperasi di 23 lokasi, yang memungkinkan anak-anak melakukan pekerjaan orang dewasa dan mendapat bayaran. KidZania telah dikunjungi oleh lebih dari 31 juta pengunjung di seluruh dunia sejak pembukaannya, menjadikannya salah satu merek hiburan global yang paling cepat berkembang di dunia.",
    place_image:
      "https://asset.kompas.com/crops/ekyCLskZGo9NLjY1SxXc0X7LY38=/0x56:1600x1123/750x500/data/photo/2022/01/20/61e9378332a03.jpeg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "185000",
    rating: "4.6",
    time_minutes: "300",
    coordinate: "{'lat': -6.225073499999999, 'lng': 106.8097144}",
    lat: "-6.225073",
    long: "106.809714",
  },
  {
    place_id: "20",
    place_name: "Museum Taman Prasasti",
    description:
      "Museum Taman Prasasti adalah sebuah museum cagar budaya peninggalan masa kolonial Belanda yang berada di Jalan Tanah Abang No. 1, Jakarta Pusat. Museum ini memiliki koleksi prasasti nisan kuno serta miniatur makam khas dari 27 provinsi di Indonesia, beserta koleksi kereta jenazah antik. Museum seluas 1,2 ha ini merupakan museum terbuka yang menampilkan karya seni dari masa lampau tentang kecanggihan para pematung, pemahat, kaligrafer dan sastrawan yang menyatu.r",
    place_image:
      "https://upload.wikimedia.org/wikipedia/commons/8/8d/Tombstones_taman_prasasti.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "2000",
    rating: "4.5",
    time_minutes: "90",
    coordinate: "{'lat': -6.172224099999998, 'lng': 106.8189695}",
    lat: "-6.172224",
    long: "106.818969",
  },
  {
    place_id: "21",
    place_name: "Museum Wayang",
    description:
      "Museum Wayang adalah sebuah museum yang berlokasi di Jalan Pintu Besar Utara Nomor 27, Jakarta Barat.",
    place_image:
      "https://upload.wikimedia.org/wikipedia/commons/b/bc/Museum_Wayang.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.5",
    time_minutes: "150",
    coordinate: "{'lat': -6.1349072, 'lng': 106.8124452}",
    lat: "-6.134907",
    long: "106.812445",
  },
  {
    place_id: "22",
    place_name: "Masjid Istiqlal",
    description:
      "Masjid Istiqlal (arti harfiah: Masjid Merdeka) adalah masjid nasional negara Republik Indonesia yang terletak di bekas Taman Wilhelmina, di Timur Laut Lapangan Medan Merdeka yang di tengahnya berdiri Monumen Nasional (Monas), di pusat ibukota Jakarta. Masjid ini merupakan salah satu dari 10 masjid terbesar kapasitasnya di dunia yang dapat menampung lebih dari 200.000 jamaah. Di seberang Timur masjid ini berdiri Gereja Katedral Jakarta. Ketua Harian Badan Pengelola Masjid Istiqlal (BPMI) sekaligus Imam Besar Masjid Istiqlal adalah Prof. Dr. Nasaruddin Umar, M.A. Pembangunan masjid ini diprakarsai oleh Presiden Republik Indonesia saat itu, Ir. Soekarno. Peletakan batu pertama sebagai tanda dimulainya pembangunan Masjid Istiqlal dilakukan oleh Ir. Soekarno pada tanggal 24 Agustus 1961. Arsitek Masjid Istiqlal adalah Frederich Silaban, seorang Nasrani.Masjid ini memiliki gaya arsitektur modern dengan dinding dan lantai berlapis marmer, dihiasi ornamen geometrik dari baja antikarat. Bangunan utama masjid ini terdiri dari lima lantai dan satu lantai dasar. Bangunan utama itu dimahkotai satu kubah besar berdiameter 45 meter yang ditopang 12 tiang besar. Menara tunggal setinggi total 96,66 meter menjulang di sudut Selatan selasar masjid. Masjid ini mampu menampung lebih dari 200.000 jamaah.Selain digunakan sebagai aktivitas ibadah umat Islam, masjid ini juga digunakan sebagai kantor berbagai organisasi Islam di Indonesia, aktivitas sosial, dan kegiatan umum. Masjid ini juga menjadi salah satu daya tarik wisata yang terkenal di Jakarta. Kebanyakan wisatawan yang berkunjung umumnya wisatawan domestik di samping sebagian wisatawan asing yang beragama Islam. Masyarakat non-Muslim juga dapat berkunjung ke masjid ini setelah sebelumnya mendapat pembekalan informasi mengenai Islam dan Masjid Istiqlal, meskipun bagian yang boleh dikunjungi kaum non-Muslim terbatas dan harus didampingi pemandu.\\nPada tiap hari besar Islam seperti Ramadhan, Idul Fitri, Idul Adha, Tahun Baru Hijriyah, Maulid Nabi Muhammad serta Isra dan Mi'raj, Presiden Republik Indonesia selalu mengadakan kegiatan keagamaan di masjid ini yang disiarkan secara langsung melalui televisi nasional (TVRI) dan sebagian televisi swasta.",
    place_image:
      "https://upload.wikimedia.org/wikipedia/id/2/25/Masjid_Istiqlal_-_Panoramio.jpg",
    category: "Tempat Ibadah",
    city: "Jakarta",
    price: "0",
    rating: "4.7",
    coordinate: "{'lat': -6.17017, 'lng': 106.83139}",
    lat: "-6.17017",
    long: "106.83139",
  },
  {
    place_id: "23",
    place_name: "Gereja Katedral",
    description:
      "Gereja Katedral Jakarta, atau bernama resmi Gereja Santa Maria Diangkat Ke Surga (bahasa Jerman: De Kerk van Onze Lieve Vrouwe ten Hemelopneming; bahasa Inggris: The Church of Our Lady of the Assumption) adalah sebuah gereja di Jakarta. Gedung gereja ini diresmikan pada 1901 dan dibangun dengan arsitektur neo-gotik dari Eropa, yakni arsitektur yang sangat lazim digunakan untuk membangun gedung gereja beberapa abad yang lalu.",
    place_image:
      "https://asset.kompas.com/crops/G9LgEB-S-kFOn4EaCO8ov5X4gKM=/0x0:0x0/750x500/data/photo/2022/05/26/628ef7d8ef338.jpg",
    category: "Tempat Ibadah",
    city: "Jakarta",
    price: "0",
    rating: "4.8",
    coordinate: "{'lat': -6.169225000000001, 'lng': 106.833063}",
    lat: "-6.169225",
    long: "106.833063",
  },
  {
    place_id: "24",
    place_name: "Museum Nasional",
    description:
      "Museum Nasional Republik Indonesia atau Museum Gajah, adalah sebuah museum arkeologi, sejarah, etnografi, dan geografi yang terletak di Jakarta Pusat dan persisnya di Jalan Merdeka Barat 12. Museum ini merupakan museum pertama dan terbesar di Asia Tenggara.",
    place_image:
      "https://kebudayaan.kemdikbud.go.id/munas/wp-content/uploads/sites/58/2018/04/UJG_8809.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.6",
    coordinate: "{'lat': -6.176402099999999, 'lng': 106.8215901}",
    lat: "-6.176402",
    long: "106.821590",
  },
  {
    place_id: "25",
    place_name: "Pasar Tanah Abang",
    description:
      "Pasar Tanah Abang atau Pasar Sabtu dibangun oleh Yustinus Vinck pada 30 Agustus 1735. Yustinus Vinck mendirikan Pasar Tanah Abang Pasar atas izin dari Gubernur Jenderal Abraham Patramini. Izin yang diberikan saat itu untuk Pasar Tanah Abang adalah untuk berjualan tekstil serta barang kelontong dan hanya buka setiap hari Sabtu. Oleh karena itu, pasar ini disebut Pasar Sabtu. Pasar ini mampu menyaingi Pasar Senen (Welter Vreden) yang sudah lebih dulu maju.\\nPada tahun 1740 terjadi Peristiwa Geger Pecinan, yaitu pembantaian orang-orang Tionghoa, perusakan harta benda, termasuk Pasar Tanah Abang diporakporandakan dan dibakar. Pada tahun 1881, Pasar Tanah Abang kembali dibangun dan yang tadinya dibuka pada hari Sabtu, ditambah hari Rabu, sehingga Pasar Tanah Abang dibuka 2 kali seminggu. Bangunan Pasar pada mulanya sangat sederhana,terdiri dari dinding bambu dan papan serta atap rumbia dari 229 papan dan 139 petak bambu. Pasar Tanah Abang terus mengalami perbaikan hingga akhir abad ke-19 dan bagian lantainya mulai dikeraskan dengan pondasi adukan. Pada tahun 1913, Pasar Tanah Abang kembali diperbaiki. Pada tahun 1926 pemerintah Batavia membongkar Pasar Tanah Abang dan diganti bangunan permanen berupa tiga los panjang dari tembok dan papan serta beratap genteng, dengan kantor pasarnya berada di atas bangunan pasar mirip kandang burung. Pelataran parkir di depan pasar menjadi tempat parkir kuda-kuda penarik delman dan gerobak. Di situ tersedia kobakan air yang cukup besar, dan di seberang jalan ada toko yang khusus menjual dedak makanan kuda. Beberapa puluh meter dari toko dedak ada sebuah gang yang dikenal sebagai Gang Madat, tempat lokalisasi para pemadat.\\nPada zaman pendudukan Jepang, pasar ini hampir tidak berfungsi, dan menjadi tempat para gelandangan.\\nPasar Tanah Abang semakin berkembang setelah dibangunnya Stasiun Tanah Abang. Di tempat tersebut mulai dibangun tempat-tempat seperti Masjid Al Makmur dan Klenteng Hok Tek Tjen Sien yang keduanya seusia dengan Pasar Tanah Abang. Pada tahun 1973, Pasar Tanah Abang diremajakan, diganti dengan 4 bangunan berlantai empat, dan sudah mengalami dua kali kebakaran, pertama tanggal 30 Desember 1978, Blok A di lantai tiga dan kedua menimpa Blok B tanggal 13 Agustus 1979. Pada tahun 1975 tercatat kiosnya ada 4.351 buah dengan 3.016 pedagang.",
    place_image:
      "https://rm.id/images/foto/med/pasar_tanah_abang_masih_sepi_34319.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4",
    time_minutes: "45",
    coordinate: "{'lat': -6.189009599999999, 'lng': 106.8119312}",
    lat: "-6.189009",
    long: "106.811931",
  },
  {
    place_id: "26",
    place_name: "Pecinan Glodok",
    description:
      "Kawasan Glodok yang dikenal sebagai pusat perdagangan elektronik sendiri dulunya merupakan bekas Penjara Glodok yang angker. Lokasi ini berada di seberang Glodok-Pancoran di kawasan Harco. Sebelum terjadi kerusuhan Mei 1998, kawasan ini sempat menjadi pusat belanja elektronik bagi wisatawan Jepang, Taiwan, dan Hongkong. Di Pinangsia, masyarakat bisa menemukan produk perlengkapan rumah tangga dan bangunan. Selain wisata belanja, pecinan Glodok-Pancoran juga merupakan situs sejarah awal mula Kota Jakarta. Setelah etnis Tionghoa bermukim dan membangun bisnis, serta perkebunan tebu, Batavia mulai berkembang pesat.",
    place_image:
      "https://assets-a1.kompasiana.com/items/album/2022/11/12/glodok1-636fca6308a8b514e20b19a3.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.3",
    time_minutes: "20",
    coordinate: "{'lat': -6.142758799999999, 'lng': 106.8140791}",
    lat: "-6.142758",
    long: "106.814079",
  },
  {
    place_id: "27",
    place_name: "Sea World",
    description:
      "Seaworld Indonesia adalah sebuah miniatur pesona laut yang terdapat dalam kompleks wisata pertama di Taman Impian Jaya Ancol.\\nPada tanggal 2 Oktober 1992, Gubernur DKI masa itu, Wiyogo Atmodarminto meletakkan batu pertama pembangunan Seaworld Indonesia. Tidak sampai dua tahun, pada tanggal 3 Juni 1994 SeaWorld Indonesia sudah mulai beroperasi. Area Seaworld seluas 3 hektare dengan luas bangunan utama 4.500 m2 berisi berbagai macam akuarium, lorong Antasena (lorong bawah air), perpustakaan, museum, terapi ikan dokter, glow theatre, komputer edukatif layar sentuh berisi informasi berbagai spesies di Seaworld dan bermacam fasilitas pelengkap untuk pengunjung seperti tempat makan, toko suvenir, dan ruang serba guna.",
    place_image:
      "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit19201280gsm/events/2021/12/08/2061b1ca-ab9f-4008-a096-68585f14754f-1638949561557-ab197ee956dec5f90a0fef1633549be4.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "115000",
    rating: "4.5",
    time_minutes: "180",
    coordinate: "{'lat': -6.126477500000001, 'lng': 106.842963}",
    lat: "-6.126477",
    long: "106.842963",
  },
  {
    place_id: "28",
    place_name: "Wisata Agro Edukatif Istana Susu Cibugary",
    description:
      "Kawasan Wisata Agro Edukatif Istana Susu “Cibugary” (Cibubur Garden Dairy ) merupakan suatu kawasan agro peternakan sapi perah bernuansa kebun dan taman. Wisata edukasi Cibubur Garden Dairy (CIBUGARY) merupakan salah wisata edukasi yang diminati siswa sekolah. Edukasi pengenalan peternakan sapi memberikan pengalaman yang tidak dapat dilupakan oleh siswa sekolah. Kegiatan edukasi yang tidak terlalu banyak dan menyenangkan ini sangat disukai siswa sekolah. Dengan berwisata edukasi ini dapat menambah ilmu dan pengalaman secara langsung bagi siswa sekolah. Paket wisata edukatif Istana Susu Cibugary dihargai antara Rp 35.000 sampai Rp 65.000 per orang. Harga tersebut sudah termasuk beberapa botol susu pasteurisasi dan goodybag cibugary.",
    place_image:
      "https://wisatajakarta.co.id/wp-content/uploads/2018/02/Cibubur-Garden-Diary.png",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "35000",
    rating: "4.5",
    coordinate: "{'lat': -6.3568093, 'lng': 106.9062371}",
    lat: "-6.356809",
    long: "106.906237",
  },
  {
    place_id: "29",
    place_name: "Wisata Kuliner Pecenongan",
    description:
      "Pecenongan merupakan salah satu surga kuliner di Jakarta Pusat yang dikenal sejak zaman Jakarta masih bernama kota Batavia. Dulunya di kawasan ini terdapat pedagang kaki lima yang menjajakan kuliner di pinggir jalan, tetapi tahun demi tahun kawasan Pecenongan semakin ramai dengan adanya rumah makan-rumah makan yang mulai dibangun. Kawasan pecenongan ini cocok bagi kalian yang ingin berwisata kuliner dimalam hari, beragam jenis kuliner yang pastinya membuat kamu kebingungan ingin mencoba yang mana terlebih dahulu. Tak heran jika orang yang sudah pernah mencoba pergi kulineran ke sini pasti akan kembali lagi.r",
    place_image:
      "https://pusat.jakarta.go.id/uploads/berita/20220131/rayakan-malam-imlekmu-di-kawasan-wisata-kuliner-pecenongan.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "5",
    coordinate: "{'lat': -6.166788700000001, 'lng': 106.8265261}",
    lat: "-6.166788",
    long: "106.826526",
  },
  {
    place_id: "30",
    place_name: "Taman Menteng",
    description:
      "Taman Menteng adalah sebuah taman yang berlokasi di kawasan Menteng, Jakarta Pusat. Taman ini dulunya ditempati oleh Stadion Menteng.\\nTaman ini berdiri di atas lahan seluas 2,9 hektar, dan memiliki koleksi 30 spesies tanaman yang berbeda. Taman Menteng juga memiliki beragam fasilitas pendukung seperti taman bermain untuk anak-anak serta lapangan futsal dan basket. Uniknya, di taman ini terdapat pula 44 sumur resapan untuk membantu penyerapan air hujan ke dalam tanah.r",
    place_image:
      "https://jakarta-tourism.sgp1.cdn.digitaloceanspaces.com/articles/963dd923-aec2-49b0-892c-bc4684f3ddc3.png",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.5",
    coordinate: "{'lat': -6.1964087, 'lng': 106.8293106}",
    lat: "-6.196408",
    long: "106.829310",
  },
  {
    place_id: "31",
    place_name: "Wisata Alam Mangrove Angke",
    description:
      "Jangan anggap di Jakarta tidak ada wisata alam. Langsung meluncur ke Jakarta Utara, tepatnya di Kamal Muara Penjaringan atau Pantai Indah Kapuk. Di daerah ini terdapat area wisata alam yaitu Taman Wisata Mangrove Jakarta yang sekarang dan beberapa tahun belakangan tengah hits. Di kawasan ini terdapat tiga area, satu berupa Suaka Margasatwa Muara Angke yang tertutup untuk umum, Hutan Mangrove milik Pemprov DKI tetapi kurang begitu menarik untuk wisata. Selanjutnya Taman Wisata Alam Mangrove Angke yang memang merupakan area wisata berbasis konservasi mangrove.r",
    place_image:
      "https://www.jakartamangrove.id/assets/images/img-2988-copy-2000x1333.jpg",
    category: "Cagar Alam",
    city: "Jakarta",
    price: "25000",
    rating: "4.3",
    coordinate: "{'lat': -6.105334, 'lng': 106.735584}",
    lat: "-6.105334",
    long: "106.735584",
  },
  {
    place_id: "32",
    place_name: "Setu Babakan",
    description:
      "Setu Babakan atau Danau Babakan terletak di Srengseng Sawah, kecamatan Jagakarsa, Kotamadya Jakarta Selatan, Indonesia dekat Depok yang berfungsi sebagai pusat Perkampungan Budaya Betawi, suatu area yang diperuntukkan untuk pelestarian warisan budaya Jakarta, yaitu budaya asli Betawi.\\nPerkampungan budaya Betawi ini didirikan pada tanggal 18 Agustus 2000 melalui Surat Keputusan Gubernur DKI Nomor 92 tahun 2000 yang dikeluarkan oleh Gubernur DKI Jakarta pada waktu itu yaitu Sutiyoso\\nSitu Babakan merupakan danau buatan dengan area 30 hektare (79 akre) dengan kedalaman 1-5 meter dimana airnya berasal dari Sungai Ciliwung dan saat ini digunakan sebagai tempat wisata alternatif, bagi warga dan para pengunjung.\\nTaman disekitarnya ditanami dengan beragam pohon buah-buahan yaitu Mangga, Palem, Melinjo, Rambutan, Jambu, Pandan, Kecapi, Jamblang, Krendang, Guni, Nangka Cimpedak, Nam-nam, dan Jengkol.\\nBanyak kuliner khas Betawi terdapat disini, antara lain Kerak Telor, Toge Goreng, Arum Manis, Rujak Bebek, Soto Betawi, Es Potong, Es Duren, Bir Pletok, Nasi Uduk, Nasi Ulam, Lontong Sayur, dll.\\nWisata budaya yang disajikan antara laim rumah-rumah khas Betawi yang dibagi menjadi 3 macam, pertama rumah Betawi gudang atau kandang, kedua rumah Betawi Kebaya atau Bapang, dan yang ketiga adalah rumah Joglo, hampir serupa dengan rumah khas Yogyakarta.\\nKeseniannya berupa Lenong, Tari Topeng, Tanjidor, Marawis, Gambang Kromong, Tari Lenggang Nyai, dan Tari Narojeng.\\nUpacara Adat yang ada di perkampungan Betawi Setu Babakan adalah Penganten Sunat, Pindah Rumah, Khatam Qur'an, dan Nujuh Bulan.\\nMayoritas penduduk di Setu Babakan adalah Betawi, dengan program dari pemda DKI untuk memperbaiki sarana dan prasarana yang ada untuk mengakomodasi kebutuhan ruang terbuka hijau, serta area untuk resapan air, setu babakan berbenah diri dengan dukungan penuh dari pemda DKI\\nFungsi dari Setu ini bukan hanya untuk tempat melestarikan kebudayaan betawi yang makin tergerus oleh zaman, tetapi digunakan juga sebagai tempat alternatif rekreasi yang berlokasi di selatan jakarta. selain fungsi utamanya sebagai penampung air resapan untuk selatan jakarta,",
    place_image:
      "https://s3.bukalapak.com/uploads/content_attachment/34064fdf10e8d762ba2b53c5/original/5-Fakta-Menarik-Setu-Babakan-Jakarta.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.4",
    coordinate: "{'lat': -6.341666699999999, 'lng': 106.8238889}",
    lat: "-6.341666",
    long: "106.823888",
  },
  {
    place_id: "33",
    place_name: "Taman Suropati",
    description:
      "Taman Suropati (awalnya bernama Burgemeester Bisschopplein) adalah nama sebuah taman di Jakarta. Pada awalnya nama taman ini diambil dari nama wali kota Batavia pertama, G.J. Bisshop (1916–1920). Taman ini merupakan pusat kawasan Menteng, berada tepat di antara pertemuan tiga jalan utama, yaitu Menteng Boulevard (Jalan Teuku Umar), Orange Boulevard (Jalan Diponegoro), dan Nassau Boulevard (Jalan Imam Bonjol). Lapangan yang kini disebut sebagai Taman Suropati ini sejak tahun 1920 sudah menggantikan lapangan bundar yang luas dalam Rencana Moojen. Taman Suropati, yang disebut-sebut sebagai titik nol Republik Indonesia, menjadi taman yang rindang dan sejak beberapa tahun yang lalu dihiasi dengan patung-patung karya pematung dari negara-negara pendiri Perhimpunan Bangsa-Bangsa Asia Tenggara.",
    place_image:
      "https://travelspromo.com/wp-content/uploads/2021/04/Salah-satu-pintu-masuk-Taman-Suropati-yoga-andika-Satria.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    coordinate: "{'lat': -6.1994034, 'lng': 106.8326228}",
    lat: "-6.199403",
    long: "106.832622",
  },
  {
    place_id: "34",
    place_name: "Pasar Taman Puring",
    description:
      "Taman Puring bukanlah taman secara harfiah. Sejak eksis di tahun 1960 silam, Taman Puring adalah sebuah pasar. Selama bertahun-tahun, pasar ini sempat menjadi pasar gelap alias pasar barang-barang ilegal. Antara tahun 1980-1990an, pasar ini makin dijauhi masyarakat karena menjadi sentra barang-barang hasil tindakan kriminal. Sejak terbakar pada 2002, Pasar Taman Puring perlahan berbenah diri hingga sekarang menjadi destinasi belanja akhir pekan favorit warga Jakarta. Ada ratusan kios sepatu pria mulai dari sepatu kulit, sepatu gunung, sepatu futsal, hingga sepatu gaul khas anak muda. Beragam merk mulai dari Adidas, Caterpillar, Nike, Karrimor, Vans, hingga Converse tersedia dalam berbagai model dan warna.",
    place_image:
      "https://salsawisata.com/wp-content/uploads/2022/12/Pasar-Taman-Puring.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.4",
    time_minutes: "60",
    coordinate: "{'lat': -6.241368999999999, 'lng': 106.7890587}",
    lat: "-6.241369",
    long: "106.789058",
  },
  {
    place_id: "35",
    place_name: "Grand Indonesia Mall",
    description:
      "Grand Indonesia merupakan mal di Jakarta. Mal ini dibuka pada tahun 2007 oleh Presiden Susilo Bambang Yudhoyono. Pada tahun 2007, Hotel Indonesia mengalami pemugaran. Selanjutnya setelah dibuka kembali, hotel dikelola oleh grup Kempinski dan namanya diganti menjadi Hotel Indonesia-Kempinski.",
    place_image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d7/Grand_Indonesia_Mall.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.7",
    time_minutes: "120",
    coordinate: "{'lat': -6.195180099999999, 'lng': 106.8204412}",
    lat: "-6.195180",
    long: "106.820441",
  },
  {
    place_id: "36",
    place_name: "Skyrink - Mall Taman Anggrek",
    description:
      "Salah satu arena ice skating Jakarta adalah Ice Skating Taman Anggrek. Area ice skating di Taman Anggrek dibuat seluas 1.248 meter persegi. Ice Skating Termegah Di Indonesia adalaH di Taman Anggrek. Tidak hanya termegah di Indonesia tetapi juga termegah di Asia.Maka dari itu tidak mengherankan bahwa banyak sekali pengunjung yang datang.",
    place_image:
      "https://cdn1-production-images-kly.akamaized.net/vfliQRCuXjOabN0GUymZyHAEy7A=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/1772578/original/090713000_1510834599-IMG_8393.JPG",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "110000",
    rating: "4.5",
    time_minutes: "180",
    coordinate: "{'lat': -6.178996, 'lng': 106.791941}",
    lat: "-6.178996",
    long: "106.791941",
  },
  {
    place_id: "37",
    place_name: "Bumi Perkemahan Cibubur",
    description:
      "Bumi Perkemahan dan Graha Wisata Pramuka Cibubur (Buperta Cibubur) adalah kawasan perkemahan yang terdapat di Cibubur, Ciracas, Jakarta Timur. Kawasan ini memiliki luas 210 hektar dan sudah berkali-kali menjadi lokasi pelaksanaan Jambore Nasional sejak tahun 1973. Buperta Cibubur dibangun di kawasan yang sebelumnya merupakan hutan karet. Pihak pengelola juga bekerja sama dengan TNI AD dan TNI AU dalam pengelolaan Buperta Cibubur.Buperta Cibubur dapat diakses dari Terminal Kampung Rambutan dengan angkutan umum jurusan Kranggan atau Mekarsari Jonggol,r",
    place_image:
      "https://1.bp.blogspot.com/-DKBE_-TGFos/Vc3I9eglsFI/AAAAAAAAARY/N9HhEOY3g9Q/s1600/buperta.JPG",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "10000",
    rating: "4.5",
    coordinate: "{'lat': -6.360248700000001, 'lng': 106.893842}",
    lat: "-6.360248",
    long: "106.893842",
  },
  {
    place_id: "38",
    place_name: "Istana Negara Republik Indonesia",
    description:
      "Istana Negara merupakan pusat kegiatan pemerintahan negara. Banyak kegiatan-kegiatan bersifat kenegaraan digelar di Istana Negara. Seperti kegiatan pelantikan pejabat-pejabat penting negara, maupun pembukaan kongres bersifat nasional dan internasional. Istana Negara fungsinya lebih difokuskan kepada kegiatan resmi kepresidenan, yaitu sebagai kantor Presiden Republik Indonesia. Dilansir situs Sekretaris Negara (Sesneg), Istana Negara awalnya sebagai kediaman pribadi warga Belanda, J.A Van Braam.",
    place_image:
      "https://blog.tiket.com/wp-content/uploads/2016/04/Istana-Negara-via-www.wikimedia.org_.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    coordinate: "{'lat': -6.168069000000001, 'lng': 106.8239727}",
    lat: "-6.168069",
    long: "106.823972",
  },
  {
    place_id: "39",
    place_name: "Museum Macan (Modern and Contemporary Art in Nusantara)",
    description:
      "Museum Seni Modern dan Kontemporer di Nusantara atau Museum MACAN adalah sebuah museum seni di Kebon Jeruk di Jakarta, Indonesia. Museum ini merupakan yang pertama di Indonesia yang memiliki koleksi seni modern dan kontemporer Indonesia dan internasional.",
    place_image:
      "https://www.kulturekween.com/wp-content/uploads/2023/07/IMG_3124-scaled.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "100000",
    rating: "4.5",
    time_minutes: "120",
    coordinate: "{'lat': -6.190942, 'lng': 106.767622}",
    lat: "-6.190942",
    long: "106.767622",
  },
  {
    place_id: "40",
    place_name: "Galeri Nasional Indonesia",
    description:
      "Galeri Nasional Indonesia (bahasa Inggris: National Gallery of Indonesia) adalah sebuah lembaga budaya negara atau sebagai museum seni rupa modern dan kontemporer. Di sini terdapat gedung yang berfungsi antara lain sebagai tempat pameran, dan perhelatan seni rupa Indonesia dan mancanegara. Gedung ini merupakan institusi milik pemerintah di bawah Menteri Pendidikan dan Kebudayaan. Fungsi Galeri Nasional Indonesia adalah melaksanakan pengkajian, pengumpulan, registrasi, perawatan, pengamanan, pameran, kemitraan, layanan edukasi dan publikasi karya seni rupa. Lalu fungsi utamanya adalah melindungi, pengembangan, dan pemanfaatan asset kesenian (seni rupa) sebagai fasilitas pendidikan dan kebudayaan. Galeri Nasional beralamat di Jalan Medan Merdeka Timur No. 14 Jakarta Pusat.r",
    place_image:
      "https://kebudayaan.kemdikbud.go.id/galerinasional/wp-content/uploads/sites/10/2021/10/Foto-Dok.-GNI-Montiari-4-scaled.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    coordinate: "{'lat': -6.178548200000001, 'lng': 106.8327716}",
    lat: "-6.178548",
    long: "106.832771",
  },
  {
    place_id: "41",
    place_name: "Museum Bahari Jakarta",
    description:
      "Museum Bahari adalah museum yang menyimpan koleksi yang berhubungan dengan kebaharian dan kenelayanan bangsa Indonesia dari Sabang hingga Merauke yang berlokasi di seberang Pelabuhan Sunda Kelapa. Museum adalah salah satu dari delapan museum yang berada di bawah pengawasan dari Dinas Kebudayaan Permuseuman Provinsi Daerah Khusus Ibu kota Jakarta.",
    place_image:
      "https://cdn.idntimes.com/content-images/post/20190724/3-aabb32cd79e3cbee616bc7bb41ad3b88.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "2000",
    rating: "4.4",
    time_minutes: "120",
    coordinate: "{'lat': -6.1269553, 'lng': 106.8085899}",
    lat: "-6.126955",
    long: "106.808589",
  },
  {
    place_id: "42",
    place_name: "Museum Seni Rupa dan Kramik",
    description:
      "Museum Seni Rupa dan Keramik (Indonesia: Museum Seni Rupa dan Keramik) adalah sebuah museum di Jakarta, Indonesia. Museum ini didedikasikan khusus untuk menampilkan seni rupa tradisional dan keramik Indonesia. Museum ini terletak di sisi timur Lapangan Fatahillah, dekat Museum Sejarah Jakarta dan Museum Wayang.",
    place_image:
      "https://dinaskebudayaan.jakarta.go.id/uploads/default/files/museum-keramik-dan-seni-rupa.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.4",
    coordinate: "{'lat': -6.1342598, 'lng': 106.814552}",
    lat: "-6.134259",
    long: "106.814552",
  },
  {
    place_id: "43",
    place_name: "The Escape Hunt",
    description:
      "Escape Hunt adalah salah satu tempat rekreasi yang lokasinya terletak di Jakarta Selatan. Di tempat ini, kamu akan berperan sebagai seorang detektif yang berada di sebuah ruangan terkunci dan hanya diberikan waktu 1 jam untuk memecahkan teka-teki yang ada. Tidak perlu khawatir atau takut sendirian, karena di sini kamu bisa mengajak hingga 4 temanmu dalam satu ruangan yang sama dan memecahkan kasus bersama-sama. Menarik sekali, bukan? Pertama kali datang di tempat ini, kamu akan dituntun untuk mengisi data di formulir yang telah disediakan dan diberikan briefing oleh pemandu game mengenai jalan cerita tema kasus yang sudah kamu tentukan.",
    place_image:
      "https://img.baysider.com/companies/1148/114807/v2_file_21298925.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "70000",
    rating: "4.4",
    time_minutes: "120",
    coordinate: "{'lat': -6.2555033, 'lng': 106.8122591}",
    lat: "-6.255503",
    long: "106.812259",
  },
  {
    place_id: "44",
    place_name: "Monumen Selamat Datang",
    description:
      "Monumen Selamat Datang adalah sebuah monumen yang terletak di tengah Bundaran Hotel Indonesia, Jakarta, Indonesia. Monumen ini berupa patung sepasang manusia yang sedang menggenggam bunga dan melambaikan tangan. Patung tersebut menghadap ke utara yang berarti mereka menyambut orang-orang yang datang dari arah Monumen Nasional.r",
    place_image:
      "https://gni.kemdikbud.go.id/assets/api/assets/poros/karya-gallery-images/c64c35df-f8fa-11eb-bc53-a3383048db70-11.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.7",
    time_minutes: "15",
    coordinate: "{'lat': -6.194997799999999, 'lng': 106.8230496}",
    lat: "-6.194997",
    long: "106.823049",
  },
  {
    place_id: "45",
    place_name: "Jakarta Aquarium dan Safari",
    description:
      "Jika telah mengunjungi Seaworld Ancol, mungkin sudah tidak asing lagi dengan serunya menyaksikan biota laut. Jika belum puas, pengunjung dapat mencoba mengunjungi wisata satwa laut unik di Jakarta Aquarium. Jakarta Aquarium menempati areal seluas ±7000 m2 ini menawarkan atraksi wisata laut modern yang tidak hanya menghibur, juga edukatif. Meskipun tidak seluas SeaWorld Ancol, taman rekreasi ini juga menawarkan wahana dan atraksi yang tak kalah menariknya.",
    place_image:
      "https://pagaralampos.disway.id/upload/8ecf92e7e56aa54e0dcfac9ff7d31a5d.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "185000",
    rating: "4.6",
    coordinate: "{'lat': -6.1752647, 'lng': 106.7904684}",
    lat: "-6.175264",
    long: "106.790468",
  },
  {
    place_id: "46",
    place_name: "Pulau Semak Daun",
    description:
      "Pulau Semak Daun merupakan salah satu pulau yang terletak digugusan kepulauan Seribu. Secara administratif pulau ini termasuk dalam wilayah kabupaten Kepulauan Seribu provinsi DKI Jakarta sebagai daerah penangkaran penyu sisik dengan pantai yang nyaman untuk berenang karena pantainya yang bersih dan landai, berpasir putih, dan bebas bulu babi, terdapat pula daerah yang bagus untuk menyelam dan snorkeling pemula dan letaknya tidak jauh dari pulau Pramuka.",
    place_image:
      "https://www.youngontop.com/wp-content/uploads/2020/07/Semak-daun.jpg",
    category: "Bahari",
    city: "Jakarta",
    price: "40000",
    rating: "4",
    coordinate: "{'lat': -5.729671599999999, 'lng': 106.5714158}",
    lat: "-5.729671",
    long: "106.571415",
  },
  {
    place_id: "47",
    place_name: "Taman Situ Lembang",
    description:
      "Taman Situ Lembang adalah sebuah taman kota yang terletak di pusat Jakarta. Situ berarti danau yang payau, sedangkan Lembang adalah nama jalan yang berada di dekat taman tersebut..\\nTaman ini merupakan salah satu taman tertua di Jakarta dan memiliki danau kecil yang airnya berasal dari sumber air alam. Di taman ini terletak fasilitas arena pemancingan, trek lari, dan arena permainan anak. Taman Situ Lembang dikelilingi oleh rumah-rumah di kawasan elite Menteng",
    place_image:
      "https://asset.kompas.com/crops/Dw6tnTK49nC2eDYeqbjc2J1C1z8=/0x0:1000x667/1200x800/data/photo/2022/04/03/624933248de4b.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.5",
    coordinate: "{'lat': -6.1978861, 'lng': 106.8346708}",
    lat: "-6.197886",
    long: "106.834670",
  },
  {
    place_id: "48",
    place_name: "Taman Ismail Marzuki",
    description:
      "Pusat Kesenian Jakarta Taman Ismail Marzuki yang populer disebut Taman Ismail Marzuki (TIM) merupakan sebuah pusat kesenian dan kebudayaan yang berlokasi di jalan Cikini Raya 73, Jakarta Pusat. Di sini terletak Institut Kesenian Jakarta dan Planetarium Jakarta. Selain itu, TIM juga memiliki enam teater modern, balai pameran, galeri, gedung arsip, dan bioskop. Acara-acara seni dan budaya dipertunjukkan secara rutin di pusat kesenian ini, termasuk pementasan drama, tari, wayang, musik, pembacaan puisi, pameran lukisan dan pertunjukan film. Berbagai jenis kesenian tradisional dan kontemporer, baik yang merupakan tradisi asli Indonesia maupun dari luar negeri juga dapat ditemukan di tempat ini. Nama pusat kesenian ini berasal dari nama pencipta lagu terkenal Indonesia, Ismail Marzuki.",
    place_image:
      "https://images-tm.tempo.co/all/2023/04/17/829293/829293_1200.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.6",
    coordinate: "{'lat': -6.1891586, 'lng': 106.8397738}",
    lat: "-6.189158",
    long: "106.839773",
  },
  {
    place_id: "49",
    place_name: "Galeri Indonesia Kaya",
    description:
      "Galeri Indonesia Kaya (disingkat GIK) adalah ruang publik yang memadukan konsep edukasi dan digital dengan tujuan untuk memperkenalkan dan mengapresiasi seni-budaya Indonesia khususnya kepada generasi muda, yang bertempat di Grand Indonesia, Jakarta, Indonesia. Galeri Indonesia Kaya digagas dan dibangun untuk menjadi ruang edutainment budaya berbasis teknologi digital yang dapat mendekatkan dan menyalurkan kreativitas berekspresi generasi muda dalam lingkup tradisi budaya nusantara. Tempat ini memiliki auditorium yang dapat digunakan untuk masyarakat yang membutuhkan tempat berkarya.",
    place_image: "https://images.soco.id/689-Galeri-Indonesia-Kaya-1.jpg.jpeg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.8",
    time_minutes: "90",
    coordinate: "{'lat': -6.1948499, 'lng': 106.8200607}",
    lat: "-6.194849",
    long: "106.820060",
  },
  {
    place_id: "50",
    place_name: "Museum Joang 45",
    description:
      "Gedung Joang '45 atau Museum Joang 45 adalah salah satu museum yang berada di Jakarta. Saat ini pengelolaannya dilaksanakan oleh Dinas Pariwisata dan Kebudayaan Provinsi DKI Jakarta. Museum ini terletak di Jalan Menteng Raya 31, Kelurahan Kebon Sirih, Kecamatan Menteng, Jakarta Pusat. Museum ini diresmikan pada tahun 1974 oleh Presiden Soeharto, setelah dilakukan renovasi.",
    place_image:
      "https://indonesiakaya.com/wp-content/uploads/2020/10/891_Halaman_depan_Gedung_Joang_45.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "2000",
    rating: "4",
    coordinate: "{'lat': -6.186183799999998, 'lng': 106.8364761}",
    lat: "-6.186183",
    long: "106.836476",
  },
  {
    place_id: "51",
    place_name: "Jakarta Planetarium",
    description:
      "Planetarium dan Observatorium Jakarta adalah satu dari tiga wahana simulasi langit di Indonesia selain di Kutai, Kalimantan Timur, dan Surabaya, Jawa Timur. Planetarium tertua ini letaknya di Taman Ismail Marzuki, Jakarta. Planetarium Jakarta merupakan sarana wisata pendidikan yang dapat menyajikan pertunjukan peragaan simulasi perbintangan atau benda-benda langit. Pengunjung diajak mengembara di jagat raya untuk memahami konsepsi tentang alam semesta melalui acara demi acara. Planetarium Jakarta berdiri tahun 1964 diprakarsai Presiden Soekarno dan diserahkan ke Pemerintah Provinsi DKI Jakarta pada 1969. Di tempat ini juga tersedia ruang pameran benda- benda angkasa yang menyuguhkan berbagai foto serta keterangan lengkap dari berbagai bentuk galaksi, teori-teori pembentukan galaksi disertai pengenalan tokoh-tokoh di balik munculnya teori.",
    place_image:
      "https://dinaskebudayaan.jakarta.go.id/encyclopedia/file/gallery/3779/b116a1b1cf5cb34ec8c334c4867a756502fd17ee.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "12000",
    rating: "4.1",
    time_minutes: "120",
    coordinate: "{'lat': -6.190081899999999, 'lng': 106.8388532}",
    lat: "-6.190081",
    long: "106.838853",
  },
  {
    place_id: "52",
    place_name: "Kampung Cina",
    description:
      "KAMPUNG China adalah hunian dan kawasan perdagangan di Cibubur, Jakarta Timur. Wilayah ini berdiri berkat kerja sama antara Pemerintah Kota Jakarta Timur dengan perusahaan asing untuk menyulap area 300 hektare kawasan wisata Cibubur menjadi kota wisata, mandiri dan town center. Mengutip buku Ensiklopedia Jakarta, kampung itu mulai beroperasi pada tanggal 14 September 2002. Bangunan, nuansa alam, sampai pernak-pernik yang dijual masih berbau kesenian China. Semua produk yang dijajahkan pun berasal dari negeri tirai bambu tersebut. Wilayah itu akan menjadi tujuan wisata pada setiap perayaan hari raya Imlek.r",
    place_image:
      "https://cdn1.katadata.co.id/media/images/2019/01/28/2019_01_28-17_42_09_f7b66c3e328424fe2970f940d7c17c4c.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "15000",
    rating: "4.5",
    coordinate: "{'lat': -6.3651357, 'lng': 106.7617984}",
    lat: "-6.365135",
    long: "106.761798",
  },
  {
    place_id: "53",
    place_name: "Rumah Sipitung",
    description: 
      "Rumah Si Pitung di Marunda, Jakarta Utara, Indonesia, merupakan satu dari sedikit rumah panggung Betawi yang tersisa. Rumah panggung ini merupakan representasi hunian panggung masyarakat Betawi yang tinggal di wilayah-wilayah Pesisir. Rumah ini menjadi museum dan masuk dalam cagar budaya. Tidak diketahui kapan persisnya Rumah Si Pitung didirikan. Diperkirakan bangunan tersebut dibangun pada abad ke-20. Rumah panggung yang sering juga disebut Rumah Tinggi Marunda ini mirip dengan rumah tradisional Suku Bugis. Rumah ini tadinya milik Haji Saipudin, seorang saudagar kaya bandar ikan asal Makassar (sumber lain mengatakan Haji Saipudin adalah juragan sero, atau konglomerat kapal). Haji Saipuddin diyakini merupakan sahabat erat Si Pitung. Pitung ditengarai hanya beberapa kali singgah di rumah itu (diperkirakan pada dasawarsa 1890-an). Singgahnya Si Pitung terakhir kali adalah dalam rangka bersembunyi dari kejaran tentara Belanda dengan tuduhan merampok. Pemerintah DKI Jakarta pertama kali memugar rumah panggung yang ditopang oleh 40 buah tiang itu pada tahun 1972. Sebelumnya pada tahun yang sama bangunan ini dibeli oleh Pemprov DKI Jakarta dari keturunan (ahli waris) H. Saipudin. Bangunan tersebut kini menjadi museum dan masuk dalam cagar budaya berdasarkan SK Gubernur No.475 tahun 1993 dan SK Menteri No.140 M 1998. Lembaga yang memberi nama rumah asli Betawi Pesisir ini sebagai rumah Si Pitung adalah Museum Nasional.",
    place_image:
      "https://asset.kompas.com/crops/rUtrIAz4XjiP0gXkruErgsmh71E=/0x0:780x390/1200x800/data/photo/2014/10/19/022556220141011-144025780x390.JPG",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.5",
    time_minutes: "90",
    coordinate: "{'lat': -6.10016, 'lng': 106.96057}",
    lat: "-6.10016",
    long: "106.96057",
  },
  {
    place_id: "54",
    place_name: "Taman Agrowisata Cilangkap",
    description:
      "Taman seluas sekitar 19 hektar ini dimiliki oleh pemerintah Provinsi (Pemprov) DKI Jakarta yang dikelola oleh Dinas Pertanian dan Kehutanan DKI. Taman Wisata Agro Cilangkap ini terletak di Jalan Raya Cilangkap No.45, Jakarta Timur. Taman ini terasa begitu permai dengan tumbuhnya aneka jenis pepohonan rindang. Kesejukan udara yang jauh dari polusi asap kendaraan bermotor, juga dapat dinikmati di taman yang dijadikan alternatif destinasi wisata bagi warga berdomisili di sekitar kawasan tersebut. Taman Wisata Agro Cilangkap juga dilengkapi dengan beberapa fasilitas seperti arena olahraga, jogging track, arena bermain anak, serta bagi sobat Ayojakarta yang memiliki hobi memancing, di sekitar area taman memiliki danau yang biasanya dijadikan area untuk memancing.",
    place_image: "https://indonesiakaya.com/wp-content/uploads/2020/10/2.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.2",
    coordinate: "{'lat': -6.340151399999999, 'lng': 106.9012561}",
    lat: "-6.340151",
    long: "106.901256",
  },
  {
    place_id: "55",
    place_name: "Klenteng Jin De Yuan",
    description:
      "Kelenteng Kim Tek Le, atau yang lebih dikenal dengan Kelenteng Jin De Yuan, sudah dibangun sejak 1650. Kelenteng yang disebut-sebut sebagai yang tertua di Jakarta ini didirikan oleh seorang Letnan Tionghoa, Kwee Hoen dan awalnya dinamakan Koan Im Teng. Jin De Yuan juga dikenal sebagai salah satu dari empat kelenteng besar yang dikelola oleh Kong Koan atau Dewan Tionghoa. Mereka adalah Kelenteng Goenoeng Sari, Kelenteng Toa Peh Kong, Kelenteng Jin De yuan sendiri, dan Kelenteng Hian Thian Shang di Tanah Tandjoeng yang kini sudah musnah.",
    place_image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Klenteng_Jin_De_Yuan%2C_Glodok%2C_Jakarta.jpg/1024px-Klenteng_Jin_De_Yuan%2C_Glodok%2C_Jakarta.jpg",
    category: "Tempat Ibadah",
    city: "Jakarta",
    price: "0",
    rating: "4.5",
    coordinate: "{'lat': -6.144473700000001, 'lng': 106.8126018}",
    lat: "-6.144473",
    long: "106.812601",
  },
  {
    place_id: "56",
    place_name: "Pantai Ancol",
    description:
      "Pantai Ancol merupakan kawasan wisata yang merupakan destinasi wisata pantai dalam kota Jakarta. Wisatawan dapat menikmati suasana segar Pantai Lagoon, Festival, Indah, Beach Pool dan Carnaval, serta Danau Impian. Berlibur di alam terbuka dipercaya memiliki efek menenangkan dan menyenangkan. Panjang garis pantainya yang kurang lebih 6,5 km menjadi tempat berbagai aktivitas wisata. Wisata pantai ini merupakan BUMD penghasil Pendapatan Asli Daerah kedua terbesar bagi provinsi DKI Jakarta.",
    place_image:
      "https://piknikwisata.com/wp-content/uploads/2020/02/info-wisata-pantai-ancol-lengkap.jpeg",
    category: "Bahari",
    city: "Jakarta",
    price: "25000",
    rating: "4.4",
    coordinate: "{'lat': -6.1194215, 'lng': 106.8502435}",
    lat: "-6.119421",
    long: "106.850243",
  },
  {
    place_id: "57",
    place_name: "Taman Lapangan Banteng",
    description:
      "Lapangan Banteng, dulu bernama Waterlooplein (bahasa Belanda: plein = lapangan) yaitu suatu lapangan yang terletak di Weltevreden, Batavia; tidak jauh dari Gereja Katedral Jakarta. Pada masa itu, Lapangan Banteng dikenal dengan sebutan Lapangan Singa[1] karena di tengahnya terpancang tugu peringatan kemenangan pertempuran di Waterloo, dengan patung singa di atasnya. Pertempuran Waterloo tersebut terjadi tanggal 18 Juni 1815 di dekat kota Waterloo, yaitu sekitar 15 km ke arah selatan dari ibu kota Belgia, Brussels. Pertempuran itu merupakan pertempuran terakhir Napoleon melawan pasukan gabungan Inggris-Belanda-Jerman. Pertempuran ini juga dicatat dalam sejarah sebagai penutup dari seratus hari sejak larinya Napoleon dari pengasingannya di pulau Elba. Sedangkan Tugu Singa tersebut didirikan pada zaman pemerintahan pendudukan tentara Jepang (1942-1945). Setelah Indonesia merdeka, namanya diganti menjadi Lapangan Banteng. Terdapat kemungkinan pada zaman dahulu tempat yang kini menjadi lapangan itu dihuni berbagai macam satwa liar seperti macan, kijang, dan banteng. Pada waktu J.P. Coen membangun kota Batavia di dekat muara Ciliwung, lapangan tersebut dan sekelilingnya masih berupa hutan belantara yang sebagian berpaya–paya. Sebelah timur dijalan Lapangan banteng timur tedapat Kantor Satlantas Polres jakarta Pusat.",
    place_image:
      "https://travelspromo.com/wp-content/uploads/2021/11/Lapangan-Banteng-Jakarta-e1635990961531.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.7",
    coordinate: "{'lat': -6.170554999999999, 'lng': 106.8350378}",
    lat: "-6.170555",
    long: "106.835037",
  },
  {
    place_id: "58",
    place_name: "Taman Ayodya",
    description:
      "Taman Ayodya, yang dulu bernama Taman Barito, adalah sebuah taman kota yang berada di Jakarta Selatan. Taman ini berlokasi di atas lahan seluas 7.500 m2, dilengkapi dengan kolam buatan seluas 1.500 m2 di tengahnya.\\nTaman Ayodya juga dilengkapi dengan jalur pijakan, kursi, gazebo, pendopo, kamar mandi, serta trek jogging.. Di dekat taman ini terdapat hotel dan pasar seperti Hotel Gran Mahakam, Plaza Blok M, Pasar Burung Barito, Mal Kebayoran Baru, dan Pasar Taman Puring.\\nTaman ini bersebelahan dengan Taman Langsat hanya dengan menyebrang jalan raya saja.",
    place_image:
      "https://getlost.id/wp-content/uploads/2021/11/Jakarta-Tourism-2.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.4",
    time_minutes: "45",
    coordinate: "{'lat': -6.245229400000001, 'lng': 106.7946655}",
    lat: "-6.245229",
    long: "106.794665",
  },
  {
    place_id: "59",
    place_name: "Museum Sumpah Pemuda",
    description:
      "Museum Sumpah Pemuda adalah sebuah museum sejarah perjuangan kemerdekaan Republik Indonesia yang berada di Jalan Kramat Raya No. 106, Jakarta Pusat dan dikelola oleh Kementerian Pendidikan dan Kebudayaan Republik Indonesia. Museum ini dibuka untuk umum, setiap hari Selasa sampai dengan Jumat dari pukul 08.00 hingga 16.00 UTC+7, setiap Sabtu dan Minggu pada pukul 08.00—16.00 WIB, dan setiap hari Senin dan hari besar nasional, museum ini ditutup untuk umum.\\nMuseum ini memiliki koleksi foto dan benda-benda yang berhubungan dengan sejarah Sumpah Pemuda 1928, serta kegiatan-kegiatan dalam pergerakan nasional kepemudaan Indonesia. Museum Sumpah Pemuda ini didirikan berdasarkan SK Gubernur DKI Jakarta pada tahun 1972 dan menjadi benda cagar budaya nasional.r",
    place_image:
      "https://forumkeadilan.com/wp-content/uploads/2023/05/Museum-Pemuda.jpeg",
    category: "Budaya",
    city: "Jakarta",
    price: "2000",
    rating: "4.7",
    coordinate: "{'lat': -6.183838799999999, 'lng': 106.8430507}",
    lat: "-6.183838",
    long: "106.843050",
  },
  {
    place_id: "60",
    place_name: "Museum Tekstil",
    description:
      "Museum cinta Tekstil menempati gedung tua di Jalan K.S. Tubun Kota Bambu Selatan No. 4 Kecamatan Palmerah, Jakarta Barat\\n\\nGedungnya sendiri pada mulanya adalah rumah pribadi seorang warga negara Prancis yang dibangun pada abad ke-19. Kemudian dibeli oleh konsul Turki bernama Abdul Azis Almussawi Al Kazimi yang menetap di Indonesia. Selanjutnya tahun 1942 dijual kepada Dr. Karel Christian Cruq.\\nPada masa perjuangan kemerdekaan Indonesia, gedung ini menjadi markas Barisan Keamanan Rakyat (BKR) dan tahun 1947 didiami oleh Lie Sion Pin. Pada tahun 1952 dibeli oleh Departemen Sosial dan pada tanggal 25 Oktober 1975 diserahkan kepada Pemda DKI Jakarta yang untuk kemudian pada tanggal 28 Juni 1976 diresmikan penggunaannya oleh Ibu Tien Soeharto sebagai Museum Tekstil.",
    place_image:
      "https://dinaskebudayaan.jakarta.go.id/encyclopedia/file/gallery/3810/f1ed48b8942734611764f96d83ca6b877d76b043.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.5",
    time_minutes: "45",
    coordinate: "{'lat': -6.187963400000002, 'lng': 106.8096081}",
    lat: "-6.187963",
    long: "106.809608",
  },
  {
    place_id: "61",
    place_name: "Tugu Proklamasi",
    description:
      "Tugu Proklamasi adalah tugu peringatan proklamasi kemerdekaan Republik Indonesia yang berdiri di kompleks Taman Proklamasi di Jalan Proklamasi, Jakarta Pusat. Taman tersebut berlokasi di bekas kediaman Sukarno di Jalan Pegangsaan Timur 56. Rumah tersebut, telah dihancurkan, adalah lokasi pembacaan proklamasi kemerdekaan.Pada kompleks juga terdapat monumen dua patung Sukarno-Hatta berukuran besar yang berdiri berdampingan, mirip dengan dokumentasi foto ketika naskah proklamasi pertama kali dibacakan. Di tengah-tengah dua patung proklamator terdapat patung naskah proklamasi terbuat dari lempengan batu marmer hitam, dengan susunan dan bentuk tulisan mirip dengan naskah ketikan aslinya.",
    place_image:
      "https://travelspromo.com/wp-content/uploads/2021/10/Tugu-Proklamasi-Jakarta-e1635748851670.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    coordinate: "{'lat': -6.2030468, 'lng': 106.8466623}",
    lat: "-6.203046",
    long: "106.846662",
  },
  {
    place_id: "62",
    place_name: "Taman Legenda Keong Emas",
    description:
      "Taman Legenda Keong Emas merupakan salah satu tempat rekreasi favorit yang ada di kawasan Jakarta Timur. Berada di dalam lokasi Taman Mini Indonesia Indah atau TMII, Taman Legenda Keong Emas TMII juga telah menjadi ikon di dalam pusat sarana wisata terbesar di Indonesia ini. Selain sebagai sarana rekreasi untuk seluruh keluarga, Taman Legenda Keong Emas TMII juga mempunyai visi dan misi untuk mengedukasi masyarakat sekaligus melestarikan warisan kebudayaan Indonesia, salah satunya melalui legenda cerita rakyat.",
    place_image:
      "https://live.staticflickr.com/1789/42598877904_636c7d28ff_b.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "30000",
    rating: "4.5",
    coordinate: "{'lat': -6.303904200000001, 'lng': 106.8936219}",
    lat: "-6.303904",
    long: "106.893621",
  },
  {
    place_id: "63",
    place_name: "Museum Kebangkitan Nasional",
    description:
      "Museum Kebangkitan Nasional (bahasa Inggris: Museum of National Awakening) adalah sebuah gedung yang dibangun sebagai monumen tempat lahir dan berkembangnya kesadaran nasional dan juga ditemukannya organisasi pergerakan modern pertama kali dengan nama Boedi Oetomo. Sebelum menjadi museum, bangunan ini dahulunya adalah sekolah kedokteran yang didirikan oleh Belanda dengan nama School tot Opleiding van Inlandsche Artsen disingkat STOVIA atau Sekolah Dokter Bumiputra. Dalam perjalanannya, gedung tersebut selalu beralih fungsi. Lokasi museum ini tidak jauh dari Pasar Senen, tepatnya di Jalan Abdurrahman Saleh No.26, sebelum RSPAD Gatot Subroto, Jakarta Pusat.",
    place_image:
      "https://kcic.co.id/lkapp/wp-content/uploads/2021/07/museum-kebangkitan-nasional.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "2000",
    rating: "4.7",
    time_minutes: "45",
    coordinate: "{'lat': -6.178352, 'lng': 106.838094}",
    lat: "-6.178352",
    long: "106.838094",
  },
  {
    place_id: "64",
    place_name: "Museum Sasmita Loka Ahmad Yani",
    description:
      "Museum Sasmita Loka Ahmad Yani adalah salah satu museum pahlawan nasional yang terletak di jalan Lembang No. 58 dan jalan Laruharhari No. 65, Jakarta Pusat, DKI Jakarta, Indonesia. Museum ini terbuka untuk umum dari hari Selasa hingga hari Minggu, dari pukul 08:00 hingga pukul 14:00 WIB. Setiap hari Senin museum ini ditutup untuk umum.",
    place_image:
      "https://assets-a1.kompasiana.com/items/album/2022/10/05/20221001-120405-633d37664addee34bb6e18f2.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "2000",
    rating: "4.7",
    time_minutes: "45",
    coordinate: "{'lat': -6.204630300000001, 'lng': 106.8365324}",
    lat: "-6.204630",
    long: "106.836532",
  },
  {
    place_id: "65",
    place_name: "Museum Basoeki Abdullah",
    description:
      "Museum Basoeki Abdullah berisi lukisan dan koleksi pribadi Basoeki Abdullah seperti patung, topeng, wayang dan senjata. Museum yang terletak di Jakarta Selatan ini dikelola oleh Kementerian Pendidikan dan Kebudayaan. Selain digunakan untuk pameran, museum ini juga digunakan untuk menggelar seminar, penelitian, lokakarya serta menerbitkan bermacam bentuk publikasi berupa katalog, biografi, kumpulan artikel dan hasil penelitian.r",
    place_image:
      "https://asset.kompas.com/crops/E7BjPcQNl36xxagK2zxl1Z4j2oY=/29x51:1578x1083/750x500/data/photo/2023/03/19/64172691ef94b.jpeg",
    category: "Budaya",
    city: "Jakarta",
    price: "1000",
    rating: "4.6",
    time_minutes: "90",
    coordinate: "{'lat': -6.289788499999998, 'lng': 106.7932681}",
    lat: "-6.289788",
    long: "106.793268",
  },
  {
    place_id: "66",
    place_name: "Museum Layang-layang",
    description:
      "Museum Layang-Layang adalah sebuah museum yang terletak di Jl. H. Kamang No. 38, Pondok Labu, Jakarta Selatan. Museum ini merupakan museum layang-layang pertama di Indonesia. Jumlah koleksi layang-layang di museum ini berjumlah 600, tetapi jumlah tersebut terus bertambah seiring datangnya koleksi-koleksi baru dari para pelayang daerah dan luar negeri maupun layang-layang yang dibuat sendiri oleh karyawan museum. Museum Layang-Layang buka setiap hari mulai pukul 09.00-16.00 WIB. Hari libur nasional Museum Layang-layang tutup.",
    place_image:
      "https://www.indoindians.com/wp-content/uploads/2016/06/koleksi-3.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "10000",
    rating: "4.5",
    time_minutes: "90",
    coordinate: "{'lat': -6.3080282, 'lng': 106.790548}",
    lat: "-6.308028",
    long: "106.790548",
  },
  {
    place_id: "67",
    place_name: "Margasatwa Muara Angke",
    description:
      "Suaka margasatwa Muara Angke adalah sebuah kawasan konservasi berdasarkan SK Menteri Kehutanan RI Nomor: 097 Kpts-II 1988, 29 Februari 1998 di wilayah hutan bakau di pesisir utara Jakarta. Secara administratif, kawasan ini termasuk wilayah Kelurahan Kapuk Muara, Kecamatan Penjaringan, Kotamadya Jakarta Utara.",
    place_image: "https://direktoripariwisata.id/imgunit/649.jpg",
    category: "Cagar Alam",
    city: "Jakarta",
    price: "25000",
    rating: "4.2",
    time_minutes: "15",
    coordinate: "{'lat': -6.1160075, 'lng': 106.7692016}",
    lat: "-6.116007",
    long: "106.769201",
  },
  {
    place_id: "68",
    place_name: "Pasar Petak Sembilan",
    description:
      "Pecinan Glodok, tepatnya di Pasar Petak Sembilan, Jakarta Barat merupakan salah satu tempat yang menjual berbagai macam kuliner khas China. Kawasan yang sebagaian besar dihuni oleh orang Tionghoa ini terkenal dengan kuliner khas China yang banyak dijajakan oleh para warga. Mulai dari kue keranjang, kue dodol, hingga kue lapis banyak dijajakan di sini. Dengan harga mulai dari Rp 30 ribu hingga Rp 100 ribu, ketiga jenis kue ini menjadi kue yang paling sering dibeli untuk melengkapi perayaan Imlek. Menurut sumber dari penjual, mereka mengaku bahwa kue yang dijajakan didatangkan langsung dari berbagai daerah. Karena berasal dari wilayah yang berbeda, kue-kue ini memilliki ciri khas tersendiri.",
    place_image:
      "https://kebudayaan.kemdikbud.go.id/wp-content/uploads/2017/01/Pecinan-Petak-Sembilan.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.4",
    time_minutes: "45",
    coordinate: "{'lat': -6.143672200000001, 'lng': 106.8129398}",
    lat: "-6.143672",
    long: "106.812939",
  },
  {
    place_id: "69",
    place_name: "Freedom Library",
    description:
      "Freedom Library adalah perpustakaan buku yang dibuka umum. Memiliki puluhan ribu koleksi buku yang disusun di rak dan sesuai dengan tema, sehingga mempermudah untuk mencari buku yang diinginkan. Dengan desain ruangan yang modern serta suasana yang tenang membuat pembaca akan betah berlama-lama disini.  Cukup dengan mendaftar menjadi member terlebih dahulu dan tidak dikenakan biaya (Gratis) kalian bisa membaca buku diperpustakaan ini.r",
    place_image:
      "https://kcic.co.id/lkapp/wp-content/uploads/2021/07/Perpustakaan-Umum-Freedom-Institute-14-2.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "5",
    coordinate: "{'lat': -6.202248200000001, 'lng': 106.8451968}",
    lat: "-6.202248",
    long: "106.845196",
  },
  {
    place_id: "70",
    place_name: "Perpustakaan Nasional",
    description:
      "Perpustakaan Nasional adalah perpustakaan yang secara khusus didirikan oleh Pemerintah Negara demi menyimpan informasi negara tersebut. Berbeda dengan perpustakaan umum, sangatlah jarang khalayak ramai diperbolehkan meminjam buku. Seringkali sebuah perpustakaan nasional menyimpan koleksi langka dan bersejarah.\\nBeberapa perpustakaan awal bisa disebut perpustakaan nasional, seperti Perpustakaan Alexandria yang merupakan Perpustakaan Mesir Kuno. Perpustakaan nasional sering kali berukuran sangat besar dan luas apalagi jika diperbandingkan dengan perpustakaan biasa lainnya di negaranya. Beberapa negara yang tidak independen, tetapi tetap berkeinginan melestarikan budaya khusus mereka umumnya mendirikan sebuah perpustakaan nasional dengan segala atribut kelembagaan tersebut deposito hukum.\\nBanyak perpustakaan nasional yang bekerja sama dengan Federasi Internasional dari Asosiasi dan Institusi Perpustakaan (bahasa Inggris: International Federation of Library Associations and Institutions (IFLA)) guna membagas tugas umum, menetapkan, dan mempromosikan standar umum serta pelaksanaan proyek untuk membantu memenuhi tugas mereka. Perpustakaan nasional di Eropa berpartisipasi dalam Perpustakaan Eropa. Ini merupakan pelayanan dari Konferensi Pustakawan Nasional Eropa (bahasa Inggris: Conference of European National Librarians (CENL)).\\nSalah satu rencana pertama dari sebuah perpustakaan nasional yang dirancang oleh matematikawan, John Dee, pada tahun 1556 yang diperlihatkan pada Mary I dari Inggris dengan rencana yang visioner untuk pelestarian buku-buku lama, manuskrip, dan catatan dan pendirian perpustakaan nasional, tetapi proposal tersebut tidak disetujui.",
    place_image:
      "https://assets-a1.kompasiana.com/items/album/2022/09/11/img-20220630-085930-01-631dbb4208a8b54dd45df6d2.jpeg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.7",
    time_minutes: "240",
    coordinate: "{'lat': -6.181291799999999, 'lng': 106.8268717}",
    lat: "-6.181291",
    long: "106.826871",
  },
  {
    place_id: "71",
    place_name: "Cibubur Garden Diary (Cibugary)",
    description:
      "Cibubur Garden Dairy atau biasa dikenal degan sebutan Cibugary merupakan sebuah perternakan sapi perah dan peternakan kambing yang memiliki nuansa kebun dikawasan Cibubur, sang empunya Bapak Rachmat Baghory mempunyai inisiatif untuk menjadikan tempat tersebut sebagai wisata agro edukatif terutama untuk anak-anak.",
    place_image:
      "https://s3.ap-southeast-1.amazonaws.com/cdn.orbit/wp-content/uploads/2021/12/31135913/covcibu-2.jpg",
    category: "Cagar Alam",
    city: "Jakarta",
    price: "50000",
    rating: "4.5",
    coordinate: "{'lat': -6.379996900000001, 'lng': 106.8949793}",
    lat: "-6.379996",
    long: "106.894979",
  },
  {
    place_id: "72",
    place_name: "Waterboom PIK (Pantai Indah Kapuk)",
    description:
      "Waterbom Jakarta merupakan sebuah wahana permainan air yang cukup populer di kawasan Pantai Indah Kapuk (PIK), Jakarta Utara. Harga tiket masuk Waterboom PIK tidak terlalu menguras kantong, hanya Rp 100 ribu per orang saat weekday atau Rp 200 ribu saat weekend. Waterboom PIK menjadi objek wisata favorit saat liburan karena menawarkan fasilitas memadai dan memiliki wahana permainan air yang terbilang lengkap.",
    place_image:
      "https://www.easybook.com/images/destination/Indonesia/Jakarta/WaterbomJakarta/WaterbomJakarta6.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "300000",
    rating: "4.4",
    coordinate: "{'lat': -6.113655899999999, 'lng': 106.7478596}",
    lat: "-6.113655",
    long: "106.747859",
  },
  {
    place_id: "73",
    place_name: "Museum Perangko",
    description:
      "Museum perangko dibangun dengan bentuk bangunan bergaya Jawa Bali di atas lahan seluas 9.590 m2 dan diresmikan oleh Presiden Soeharto pada tanggal 29 September 1983. Museum ini memamerkan koleksi perangko asal Indonesia dan luar negeri. Adapula sepeda pos antik merk Falter buatan Jerman Barat tahun 1950 diletakkan di serambi museum. Halaman depan ada bola dunia dengan merpati yang membawa sebuah surat yang melambangkan bahwa tugas Perum Pos dan Giro menjangkau seluruh dunia.",
    place_image:
      "https://jakarta-tourism.sgp1.cdn.digitaloceanspaces.com/images/article/8554606681664199508.jpg ",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.4",
    coordinate: "{'lat': -6.304184100000001, 'lng': 106.9017725}",
    lat: "-6.304184",
    long: "106.901772",
  },
  {
    place_id: "74",
    place_name: "Museum Tengah Kebun",
    description:
      "Museum di Tengah Kebun adalah sebuah museum penyimpanan ± 4.000 koleksi seni dan sejarah Indonesia dan luar negeri yang berlokasi di daerah Kemang, Jakarta Selatan. Museum ini dibangun di tengah kebun seluas 3.500 m2. Museum ini dimiliki secara pribadi oleh Sjahrial Djalil, salah satu tokoh periklanan modern Indonesia dan pendiri biro iklan Ad Force Inc. Pada tahun 2013, museum ini terpilih sebagai Museum Swasta Terbaik di Museum Awards dengan koleksi dari 63 negara dan 26 provinsi di Indonesia.[2] Hal yang membuat museum ini berbeda dari museum lainnya adalah penataan sebanyak 2.414 koleksi yang dipamerkan kepada pengunjung diletakkan tidak beraturan di berbagai sudut ruangan, seperti lantai, tangah taman, toilet, dinding luar rumah, dan lain sebagainya.",
    place_image:
      "https://blog.amartha.com/wp-content/uploads/2020/01/Lorong-hijau-museum.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    time_minutes: "120",
    coordinate: "{'lat': -6.267513, 'lng': 106.824107}",
    lat: "-6.267513",
    long: "106.824107",
  },
  {
    place_id: "75",
    place_name: "SnowBay Waterpark",
    description:
      "Waterpark yang menghadirkan wahana imajinatif berkonsep pegunungan bersalju. Tidak ketinggalan dengan atraksi air terbaik yang sangat menyenangkan. Dengan luas sekitar 3 hektar, tempat wisata ini menyediakan wahana – wahana permainan air terbaik. Tak salah jika water park ini diminati dan dipadati oleh pengunjung terutama saat musim liburan datang. Pengunjung dapat menikmati keseruan berbagai atraksi air dengan pemandangan artistik yang menutupi 70% kawasan dengan salju. Pengunjung dapat merasakan rasa lelah dan penat berkurang hanya dengan menyaksikan suasana salju eksotik ini. Pengunjung akan disambut dengan rekreasi air berkelas dunia dengan konsep petualangan yang akan membuat terkesima. Menyuguhkan berbagai aktivitas seru yang dapat dinikmati oleh seluruh keluarga dari segala umur. Tidak hanya permainan air, terdapat juga wahana yang menantang adrenalin, cocok bagi yang ingin melepas stres.",
    place_image:
      "https://wisato.id/wp-content/uploads/2022/10/SnowBay-Waterpark-TMII-1.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "180000",
    rating: "4.3",
    coordinate: "{'lat': -6.299271800000001, 'lng': 106.89151}",
    lat: "-6.299271",
    long: "106.89151",
  },
  {
    place_id: "76",
    place_name: "Taman Cattleya",
    description:
      "Kehadiran Taman Cattleya tentu saja sangat bermanfaat bagi masyarakat Ibu Kota, ditengah situasi penatnya kemacetan, tumpukkan pekerjaan, serta polusi yang menjadi ancaman bagi kota-kota besar. Lokasi Taman Cattleya sangat strategis bagi mereka anda yang sedang bingung mencari tempat yang pas di akhir pekan. Lokasi Taman Cattleya berada di dekat pusat perbelanjaan yang sangat terkenal, yaitu Mall Taman Anggrek.",
    place_image:
      "https://hariliburnasional.com/wp-content/uploads/2018/12/Rute-ke-Taman-Cattleya-Tomang-Jakarta-Barat.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "20000",
    rating: "4.5",
    coordinate: "{'lat': -6.181084299999999, 'lng': 106.7954476}",
    lat: "-6.181084",
    long: "106.795447",
  },
  {
    place_id: "77",
    place_name: "Taman Hutan Tebet",
    description:
      "Taman Tebet dibangun tahun 1960, taman ini sempat tertunda di tahun 1970 dan jadi pemukiman liar sampai tahun 2006. Dahulu, namanya Taman Honda. Bukan tanpa alasan, dinamakan demikian karena restorasi taman ini dilakukan atas kerjasama PT Honda Prospect Motor dan Pemerintah Provinsi DKI Jakarta. Taman seluas 1.800 m2 yang diresmikan oleh gubernur DKI Jakarta (waktu itu) Fauzi Bowo tanggal 28 Juli 2010. Merupakan ruang terbuka hijau yang dapat dimanfaatkan warga Jakarta untuk beraktivitas. Berada di antara jalan Tebet Barat Raya dan jalan Tebet Timur Raya Kecamatan Tebet, Kotamadya Jakarta Selatan. Kawasan taman memiliki anak sungai yang mengalir dari arah Pasarminggu menuju ke Manggarai. Taman Tebet juga dilengkapi dengan sejumlah fasilitas, seperti arena bermain untuk anak dan tempat berolahraga. Untuk arena olahraga sendiri, ada bulu tangkis dan jogging track. Taman yang dirawat oleh petugas ini juga menyediakan musala, kamar mandi, gazebo, dan fasilitas terapi refleksi.",
    place_image:
      "https://wisatamilenial.com/wp-content/uploads/2022/06/Jembatan-Merah-di-Tebet-Eco-Park-Image-From-@lutfylufthansyah.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.4",
    time_minutes: "60",
    coordinate: "{'lat': -6.237140900000001, 'lng': 106.8526505}",
    lat: "-6.237140",
    long: "106.852650",
  },
  {
    place_id: "78",
    place_name: "Hutan Kota Srengseng",
    description:
      "Selain Taman Hutan Mangrove dan Pantai Indah Kapuk, salah satu taman yang sudah cukup terkenal lama bisa dijumpai di sekitar Universitas Indonesia Depok, letaknya di pinggiran Jakarta, namanya Hutan Kota Srengseng. Sesuai namanya, kawasan wisata ini terletak di daerah Srengseng Kembangan Jakbar, letaknya dekat dengan daerah Kemayoran, Kebon Jeruk serta Rawa Buaya. Hutan Srengseng ini menjadi salah satu kawasan alam hijua yang bisa dijumpai di Daerah Khusus Ibukota Jakarta. Namun perlu diketahui bukan Srengseng Sawah ya, itu sudah berbeda. Kehadiran Taman Kota ini memberikan peran penting di sektor alam Jakarta yang tengah mengalami perkembangan cukup pesat.",
    place_image:
      "https://pingpoint.co.id/media/images/PURI_KEMBANGAN_KAWASAN_MENIKMATI_UDARA_SEGAR_DI.original.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "1000",
    rating: "4.3",
    coordinate: "{'lat': -6.210694499999999, 'lng': 106.7643954}",
    lat: "-6.210694",
    long: "106.764395",
  },
  {
    place_id: "79",
    place_name: "Taman Spathodea",
    description:
      "Objek Wisata Taman Spathodea di Jagakarsa DKI Jakarta Selatan Jakarta adalah salah satu tempat wisata yang berada di Jl. Kebagusan Raya, Kecamatan Jagakarsa, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia. Objek Wisata Taman Spathodea di Jagakarsa DKI Jakarta Selatan Jakarta adalah tempat wisata yang ramai dengan wisatawan pada hari biasa maupun saat liburan. Yang menjadi daya tarik Taman Spathodea memiliki banyak jenis tanaman yang ditanam baik pepohonan dan bunga-bunga yang menghiasi area taman. Ada danau kecil yang berada ditengah taman akan membuat nyaman pengunjung. Banyak Fasilitas umum juga tersedia di Taman Spathodea seperti misalnya lintasan jogging, kolam ikan, outdoor gym, taman bermain untuk anak-anak, toilet, parkiran yang cukup luas dan tempat duduk yang cukup nyaman. Taman Spathodea ini hanya buka mulai pukul 05.00 – 18.00 WIB jadi kalo sudah mulai malam taman ini akan ditutup untuk umum.",
    place_image:
      "https://mytrip123.com/wp-content/uploads/2022/10/taman-spathodea.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    time_minutes: "30",
    coordinate: "{'lat': -6.3226133, 'lng': 106.8241871}",
    lat: "-6.322613",
    long: "106.824187",
  },
  {
    place_id: "80",
    place_name: "Plaza Indonesia",
    description:
      "Plaza Indonesia diresmikan pada awal tahun 1990, terdiri dari empat lantai pertokoan kelas atas dengan luas 38.050 m2. Pusat perbelanjaan ini terletak di Bundaran Hotel Indonesia, tepatnya pada perantara jalan M.H. Thamrin dan jalan Kebon Kacang Raya di kawasan bisnis utama Jakarta.\\nPlaza Indonesia juga dilengkapi dengan hotel Grand Hyatt Jakarta, sebuah hotel bintang lima berlantai 28 yang resmi dibuka juga pada awal tahun 1990. Hotel ini memiliki lebih dari 300 kamar dengan desain modern minimalis, restoran-restoran eksklusif, dan fasilitas yang sangat lengkap.\\nPengembangan Plaza Indonesia berlanjut ketika Entertainment X'nter dibuka disebelah gedung yang ada dengan membidik pangsa pasar anak muda. Kedua gedung disambung dengan sebuah jembatan yang dikelilingi toko-toko.\\nKini, Plaza Indonesia telah dilengkapi dengan gedung perkantoran The Plaza Office Tower dan apartement The Keraton Grand Hyatt Residences.\\nPlaza Indonesia dikembangkan oleh PT Global Land Development Tbk (sebelumnya bernama PT Kridaperdana Indahgraha Tbk).",
    place_image:
      "https://img2.beritasatu.com/cache/beritasatu/960x620-3/1399473598.JPG",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.7",
    time_minutes: "120",
    coordinate: "{'lat': -6.193925900000002, 'lng': 106.8222158}",
    lat: "-6.193925",
    long: "106.822215",
  },
  {
    place_id: "81",
    place_name: "Mall Thamrin City",
    description:
      "Thamrin City atau Thamrin City Mall merupakan pusat perbelanjaan besar yang berada di Jakarta Pusat, yang lokasinya terletak ± 150 meter dari bundaran Hotel Indonesia dan ± 300 meter dari Pasar Tanah Abang, yang tepatnya berada di Jl. Thamrin Boulevard (d h Kebon Kacang Raya) dengan akses berbagai arah antara lain dari Jl. Thamrin, Jl. Teluk Betung, maupun dari Jl. KH. Mas Mansyur",
    place_image:
      "https://advontura.com/wp-content/uploads/2021/01/thamrin-city-mall-3-1.jpg",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.4",
    time_minutes: "60",
    coordinate: "{'lat': -6.1946096, 'lng': 106.817905}",
    lat: "-6.194609",
    long: "106.817905",
  },
  {
    place_id: "82",
    place_name: "Museum Satria Mandala",
    description:
      "Museum Satria Mandala adalah museum sejarah perjuangan Tentara Nasional Indonesia yang terletak di Jalan Gatot Subroto, Jakarta Selatan. Museum yang diresmikan pada tahun 1972 oleh mantan Presiden Indonesia, Soeharto ini awalnya adalah rumah dari salah satu istri mantan Presiden Indonesia, Soekarno, yaitu istrinya yang bernama Ratna Sari Dewi Soekarno. Dalam museum ini dapat ditemui berbagai koleksi peralatan perang di Indonesia, dari masa lampau hingga modern seperti koleksi ranjau, rudal, torpedo, tank, meriam bahkan helikopter dan pesawat terbang (satu di antaranya adalah pesawat Cureng yang pernah diterbangkan oleh Marsekal Udara Agustinus Adisucipto).\\nSelain itu museum ini juga menyimpan berbagai macam benda bersejarah yang berkaitan dengan TNI seperti aneka senjata berat maupun ringan, atribut ketentaraan, panji-panji dan lambang-lambang di lingkungan TNI. Selain itu di museum ini dipamerkan juga tandu yang dipergunakan untuk mengusung Panglima Besar Jenderal Soedirman saat dia bergerilya dalam keadaan sakit melawan pendudukan kembali Belanda pada era 1940-an.\\nMasih dalam kompleks Museum TNI Satriamandala ini terdapat juga Museum Waspada Purbawisesa yang menampilkan diorama ketika TNI bersama-sama dengan rakyat menumpas gerombolan separatis DI TII di Jawa Barat, Jawa Tengah, Aceh, Kalimantan Selatan dan Sulawesi Selatan pada era tahun 1960-an. Fasilitas lainnya yang ada di Museum TNI Satriamandala ini antara lain adalah Taman Bacaan Anak, Kios Cenderamata, Kantin serta Gedung Serbaguna yang berkapasitas 600 kursi.",
    place_image:
      "https://binaqurani.sch.id/wp-content/uploads/2021/11/Bina-Qurani-Sejarah-Museum-Satria-Mandala-From-Tagar-id.jpg",
    category: "Budaya",
    city: "Jakarta",
    price: "5000",
    rating: "4.5",
    time_minutes: "150",
    coordinate: "{'lat': -6.231698499999999, 'lng': 106.8185425}",
    lat: "-6.231698",
    long: "106.818542",
  },
  {
    place_id: "83",
    place_name: "Alive Museum Ancol",
    description:
      "Museum kini tidak hanya menawarkan benda – benda yang bernilai sejarah dan edukatif. Tapi telah disulap menjadi wahana rekreasi seru dengan objek foto yang berbeda. Seperti Alive Museum yang ada di Ancol. Alive Museum menampilkan berbagai seni rupa berupa lukisan 3 dimensi. Dimana pengunjung dapat berfoto dengan latar belakang yang nyata meski hanya dari foto. Dan karena 3 dimensi, tentu foto akan terlihat nyata dengan objeknya.",
    place_image:
      "https://farm1.staticflickr.com/925/42560125254_ef21acdbd1_c.jpg",
    category: "Taman Hiburan",
    city: "Jakarta",
    price: "200000",
    rating: "4.3",
    coordinate: "{'lat': -6.117534399999999, 'lng': 106.857313}",
    lat: "-6.117534",
    long: "106.857313",
  },
  {
    place_id: "84",
    place_name: "Kawasan Kuliner BSM",
    description:
      "Tidak seperti Pecenongan, Kawasan Kuliner BSM buka dari pukul 09:00 hingga 18:00. Berlokasi di Jalan M. H. Thamrin, Jakarta Pusat, Kawasan Kuliner BSM merupakan tempat makan murah favorit warga sekitar serta pelancong. Kawasan kuliner Jakarta ini menghadirkan kios dan warung yang berderet di satu area khusus. Pengunjung bisa menyusuri jalur sempit di antara tiap kios untuk memilih hidangan. Kawasan Kuliner BSM menghadirkan hidangan berat dan makanan ringan. Pengunjung bisa menemukan bakso, nasi goreng, aneka soto, nasi Padang, nasi uduk, pecel, sete, gudeg, gado-gado, dan sebagainya. Ada juga berbagai hidangan ringan dan kue-kue, seperti misalnya donat kentang, jamur goreng, sup buah, kentang goreng, dan beragam gorengan. Pengunjung bisa naik bus Trans Jakarta koridor 1 (Blok M-Kota) hingga ke Halte Bank Indonesia, lalu menyeberang jalan ke dekat gedung Bank Mandiri. Dari sana, Kawasan Kuliner BSM cukup mudah ditemukan.",
    place_image:
      "https://1.bp.blogspot.com/-70SnWFb2-0s/WYhC8HApybI/AAAAAAAAAVU/iqMRguP285QMTegBh340BEzqgvtIgQyzgCLcBGAs/s1600/IMG_4054.JPG",
    category: "Pusat Perbelanjaan",
    city: "Jakarta",
    price: "0",
    rating: "4.6",
    coordinate: "{'lat': -6.184258799999999, 'lng': 106.824033}",
    lat: "-6.184258",
    long: "106.824033",
  },
]